MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY"

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".start"
Content-Type: text/plain

fplayback -i on -r off -f 1 -e on -h on -t on -a on -k on -s 1
tcur 0
fps 24
tset 0 10
frange 1 240
unitlength 1
unitmass 1
prompt '`strcat(oppwf(), " -> ")`'

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".variables"
Content-Type: text/plain

set -g ACTIVETAKE = 'Main'
set -g E = '2.7182818284590452354'
set -g EYE = 'stereo'
set -g HIP = 'D:/VFX/WOK_ANIMATION/Wok_Animation'
set -g HIPFILE = 'D:/VFX/WOK_ANIMATION/Wok_Animation/WOK_ANIM_txt.HIP'
set -g HIPNAME = 'WOK_ANIM_txt'
set -g JOB = 'D:/VFX/WOK_ANIMATION/Wok_Animation'
set -g PI = '3.1415926535897932384'
set -g POSE = 'C:/Users/hrist/OneDrive/Music/Documents/houdini18.5/poselib'
set -g _HIP_SAVEPLATFORM = 'windows-x86_64-cl19.16'
set -g _HIP_SAVETIME = 'Tue Mar  2 23:39:32 2021'
set -g _HIP_SAVEVERSION = '18.5.408'
set -g status = '0'

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".aliases"
Content-Type: text/plain

alias bye 'quit'
alias cd 'opcf'
alias cp 'opcp'
alias h 'history'
alias hython 'python'
alias ls 'opls'
alias matramp 'opramp'
alias opcd 'opcf'
alias oppwd 'oppwf'
alias pwd 'oppwf'
alias rm 'oprm'

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".takeconfig"
Content-Type: text/plain

takename -g take

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".hou.session"
Content-Type: text/plain


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".OPlibraries"
Content-Type: text/plain


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".OPpreferences"
Content-Type: text/plain


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".OPfallbacks"
Content-Type: text/plain

Top/localscheduler C:/PROGRA~1/SIDEEF~1/HOUDIN~1.408/houdini/otls/OPlibTop.hda
Top/localscheduler otls/OPlibTop.hda

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".OPdummydefs"
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64

SU5EWAAAAAAAAAAAAAAAAwAAAA1JTkRFWF9TRUNUSU9OAAAAAAAAANBgPr6kAAAAEmhvdWRpbmkuaGRhbGlicmFyeQAAANAAAAAAYD6+pAAAABJUb3AvbG9jYWxzY2hlZHVsZXIAAADQAAAl6mA+uMQAAAABAAAABQAAAA5sb2M=
YWxzY2hlZHVsZXIAAAAPTG9jYWwgU2NoZWR1bGVyAAAALG9wbGliOi9Ub3AvbG9jYWxzY2hlZHVsZXI/VG9wL2xvY2Fsc2NoZWR1bGVyAAAAElRPUF9sb2NhbHNjaGVkdWxlcgAAAAAAAAAAAAAAA1RvcAAAAAAAAAAAAAAAAAA=
AAArc3VidHlwZT1sb2NhbHNjaGVkdWxlciBwZGd0eXBlPSdzY2hlZHVsZXInIAAAAAAAAAAAYD6+pAABAAAAAABJTkRYAAAAAAAAAAAAAAABAAAADERpYWxvZ1NjcmlwdAAAAAAAACW+X5Jb0iMgRGlhbG9nIHNjcmlwdCBmb3I=
IGxvY2Fsc2NoZWR1bGVyIGF1dG9tYXRpY2FsbHkgZ2VuZXJhdGVkCgp7CiAgICBuYW1lCWxvY2Fsc2NoZWR1bGVyCiAgICBzY3JpcHQJbG9jYWxzY2hlZHVsZXIKICAgIGxhYmVsCSJMb2NhbCBTY2hlZHVsZXIiCgogICAgaGU=
bHAgewoJIiIKICAgIH0KCiAgICBncm91cCB7CiAgICAgICAgbmFtZSAgICAiZm9sZGVyMCIKICAgICAgICBsYWJlbCAgICJTY2hlZHVsZXIiCgogICAgICAgIGdyb3Vwc2ltcGxlIHsKICAgICAgICAgICAgbmFtZSAgICAiZm8=
bGRlcjQiCiAgICAgICAgICAgIGxhYmVsICAgIlBhdGhzIgoKICAgICAgICAgICAgcGFybSB7CiAgICAgICAgICAgICAgICBuYW1lICAgICJwZGdfd29ya2luZ2RpciIKICAgICAgICAgICAgICAgIGxhYmVsICAgIldvcmtpbmc=
IERpcmVjdG9yeSIKICAgICAgICAgICAgICAgIHR5cGUgICAgZGlyZWN0b3J5CiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIiRISVAiIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICA=
ICBuYW1lICAgICJwZGdfbWFwbW9kZSIKICAgICAgICAgICAgICAgIGxhYmVsICAgIlBhdGggTWFwcGluZyIKICAgICAgICAgICAgICAgIHR5cGUgICAgb3JkaW5hbAogICAgICAgICAgICAgICAgZGVmYXVsdCB7ICIwIiB9CiA=
ICAgICAgICAgICAgICAgbWVudSB7CiAgICAgICAgICAgICAgICAgICAgIjAiICJHbG9iYWwiCiAgICAgICAgICAgICAgICAgICAgIjEiICJOb25lIgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgcGFybXRhZyA=
eyAic2NyaXB0X2NhbGxiYWNrX2xhbmd1YWdlIiAicHl0aG9uIiB9CiAgICAgICAgICAgIH0KICAgICAgICAgICAgcGFybSB7CiAgICAgICAgICAgICAgICBuYW1lICAgICJwZGdfdXNlbWFwem9uZSIKICAgICAgICAgICAgICA=
ICBsYWJlbCAgICJVc2UgUGF0aCBNYXAgWm9uZSIKICAgICAgICAgICAgICAgIHR5cGUgICAgdG9nZ2xlCiAgICAgICAgICAgICAgICBub2xhYmVsCiAgICAgICAgICAgICAgICBqb2lubmV4dAogICAgICAgICAgICAgICAgZGU=
ZmF1bHQgeyAiMCIgfQogICAgICAgICAgICAgICAgZGlzYWJsZXdoZW4gInsgcGRnX21hcG1vZGUgPT0gMSB9IgogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0=
CiAgICAgICAgICAgIH0KICAgICAgICAgICAgcGFybSB7CiAgICAgICAgICAgICAgICBuYW1lICAgICJwZGdfbWFwem9uZSIKICAgICAgICAgICAgICAgIGxhYmVsICAgIlBhdGggTWFwIFpvbmUiCiAgICAgICAgICAgICAgICA=
dHlwZSAgICBzdHJpbmcKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiJFBER19QQVRITUFQX1pPTkUiIH0KICAgICAgICAgICAgICAgIGRpc2FibGV3aGVuICJ7IHBkZ191c2VtYXB6b25lID09IDAgfSIKICAgICAgICAgICA=
ICAgICBtZW51cmVwbGFjZSB7CiAgICAgICAgICAgICAgICAgICAgIlBPU0lYIiAiUE9TSVgiCiAgICAgICAgICAgICAgICAgICAgIldJTiIgICAiV0lOIgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgcGFybXQ=
YWcgeyAic2NyaXB0X2NhbGxiYWNrX2xhbmd1YWdlIiAicHl0aG9uIiB9CiAgICAgICAgICAgIH0KICAgICAgICB9CgogICAgICAgIHBhcm0gewogICAgICAgICAgICBuYW1lICAgICJzb2NrZXRjYWxsYmFja3MiCiAgICAgICA=
ICAgICBsYWJlbCAgICJVc2UgU29ja2V0IGNhbGxiYWNrcyBpbnN0ZWFkIG9mIHN0ZG91dCB0b2tlbnMiCiAgICAgICAgICAgIHR5cGUgICAgaW50ZWdlcgogICAgICAgICAgICBpbnZpc2libGUKICAgICAgICAgICAgZGVmYXU=
bHQgeyAiMSIgfQogICAgICAgICAgICByYW5nZSAgIHsgMCAxMCB9CiAgICAgICAgfQogICAgICAgIGdyb3Vwc2ltcGxlIHsKICAgICAgICAgICAgbmFtZSAgICAiZm9sZGVyNSIKICAgICAgICAgICAgbGFiZWwgICAiU2NoZWQ=
dWxpbmciCgogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgIm1heHByb2NzbWVudSIKICAgICAgICAgICAgICAgIGxhYmVsICAgIlRvdGFsIFNsb3RzIgogICAgICAgICAgICAgICAgdHlwZSAgICA=
b3JkaW5hbAogICAgICAgICAgICAgICAgam9pbm5leHQKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiMCIgfQogICAgICAgICAgICAgICAgbWVudSB1c2V0b2tlbnZhbHVlIHsKICAgICAgICAgICAgICAgICAgICAiMCIgICA=
ICAiRXF1YWwgdG8gMS80IG9mIFRvdGFsIENQVSBDb3VudCIKICAgICAgICAgICAgICAgICAgICAiLTEiICAgICJFcXVhbCB0byBDUFUgQ291bnQgTGVzcyBPbmUiCiAgICAgICAgICAgICAgICAgICAgIjEiICAgICAiQ3VzdG8=
bSBTbG90IENvdW50IgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibWF4cHJvY3MiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJtYXg=
cHJvY3MiCiAgICAgICAgICAgICAgICB0eXBlICAgIGludGVnZXIKICAgICAgICAgICAgICAgIG5vbGFiZWwKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiMSIgfQogICAgICAgICAgICAgICAgZGlzYWJsZXdoZW4gInsgbWE=
eHByb2NzbWVudSAhPSAxIH0iCiAgICAgICAgICAgICAgICByYW5nZSAgIHsgLTQgMTI4IH0KICAgICAgICAgICAgICAgIHBhcm10YWcgeyAiYXV0b3Njb3BlIiAiMDAwMDAwMDAwMDAwMDAwMCIgfQogICAgICAgICAgICB9CiA=
ICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgInZlcmJvc2UiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJWZXJib3NlIExvZ2dpbmciCiAgICAgICAgICAgICAgICB0eXBlICAgIHRvZ2dsZQogICA=
ICAgICAgICAgICAgIGRlZmF1bHQgeyAiMCIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0KICAgICAgICAgICAgfQogICAgICAgIH0KCiAgICAgICAgZ3I=
b3Vwc2ltcGxlIHsKICAgICAgICAgICAgbmFtZSAgICAiZm9sZGVyMSIKICAgICAgICAgICAgbGFiZWwgICAiVGVtcCBEaXJlY3RvcnkiCgogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgInRlbXA=
ZGlybWVudSIKICAgICAgICAgICAgICAgIGxhYmVsICAgIkxvY2F0aW9uIgogICAgICAgICAgICAgICAgdHlwZSAgICBvcmRpbmFsCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjEiIH0KICAgICAgICAgICAgICAgIG1lbnU=
IHsKICAgICAgICAgICAgICAgICAgICAiMCIgIldvcmtpbmcgRGlyZWN0b3J5IgogICAgICAgICAgICAgICAgICAgICIxIiAiSG91ZGluaSBUZW1wIgogICAgICAgICAgICAgICAgICAgICIyIiAiQ3VzdG9tIgogICAgICAgICA=
ICAgICAgIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgInRlbXBkaXJhcHBlbmRwaWQiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJBcHBlbmQgUElEIgogICAgICA=
ICAgICAgICAgIHR5cGUgICAgdG9nZ2xlCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjEiIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgInRlbXBkaXJjdXN0b20=
IgogICAgICAgICAgICAgICAgbGFiZWwgICAiQ3VzdG9tIgogICAgICAgICAgICAgICAgdHlwZSAgICBkaXJlY3RvcnkKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiJEhPVURJTklfVEVNUF9ESVIvJEhJUE5BTUUvcGRndGU=
bXAiIH0KICAgICAgICAgICAgICAgIGRpc2FibGV3aGVuICJ7IHRlbXBkaXJtZW51ICE9IDIgfSIKICAgICAgICAgICAgfQogICAgICAgIH0KCiAgICB9CgogICAgZ3JvdXAgewogICAgICAgIG5hbWUgICAgImZvbGRlcjBfMSI=
CiAgICAgICAgbGFiZWwgICAiSm9iIFBhcm1zIgoKICAgICAgICBncm91cHNpbXBsZSB7CiAgICAgICAgICAgIG5hbWUgICAgImZvbGRlcjBfMiIKICAgICAgICAgICAgbGFiZWwgICAiU2NoZWR1bGluZyIKCiAgICAgICAgICA=
ICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgImxvY2FsX3NpbmdsZSIKICAgICAgICAgICAgICAgIGxhYmVsICAgIlNpbmdsZSIKICAgICAgICAgICAgICAgIHR5cGUgICAgdG9nZ2xlCiAgICAgICAgICAgICAgICA=
ZGVmYXVsdCB7ICIwIiB9CiAgICAgICAgICAgICAgICByYW5nZSAgIHsgMCAxMCB9CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInBkZzo6c2NoZWR1bGVyIiAiIiB9CiAgICAgICAgICAgIH0KICAgICAgICAgICAgcGFybSA=
ewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWxfaXNfQ1BVX251bWJlcl9zZXQiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJsb2NhbF9pc19DUFVfbnVtYmVyX3NldCIKICAgICAgICAgICAgICAgIHR5cGUgICAgdG8=
Z2dsZQogICAgICAgICAgICAgICAgbm9sYWJlbAogICAgICAgICAgICAgICAgam9pbm5leHQKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiMCIgfQogICAgICAgICAgICAgICAgcmFuZ2UgICB7IDAgMSB9CiAgICAgICAgICA=
ICAgICAgcGFybXRhZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWxfQ1BVc190b191c2UiCiAgICAgICAgICAgICA=
ICAgbGFiZWwgICAiU2xvdHMgUGVyIFdvcmsgSXRlbSIKICAgICAgICAgICAgICAgIHR5cGUgICAgaW50ZWdlcgogICAgICAgICAgICAgICAgZGVmYXVsdCB7ICIxIiB9CiAgICAgICAgICAgICAgICBkaXNhYmxld2hlbiAieyA=
bG9jYWxfaXNfQ1BVX251bWJlcl9zZXQgPT0gMCB9IgogICAgICAgICAgICAgICAgcmFuZ2UgICB7IDEhIDY0IH0KICAgICAgICAgICAgICAgIHBhcm10YWcgeyAicGRnOjpzY2hlZHVsZXIiICIiIH0KICAgICAgICAgICAgfQo=
ICAgICAgICB9CgogICAgICAgIGdyb3Vwc2ltcGxlIHsKICAgICAgICAgICAgbmFtZSAgICAiZm9sZGVyMiIKICAgICAgICAgICAgbGFiZWwgICAiVGFza3MiCgogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG4=
YW1lICAgICJsb2NhbF9lY2hhbmRsZWJ5IgogICAgICAgICAgICAgICAgbGFiZWwgICAiT24gVGFzayBGYWlsdXJlIgogICAgICAgICAgICAgICAgdHlwZSAgICBvcmRpbmFsCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjA=
IiB9CiAgICAgICAgICAgICAgICBtZW51IHsKICAgICAgICAgICAgICAgICAgICAiMCIgIlJlcG9ydCBFcnJvciIKICAgICAgICAgICAgICAgICAgICAiMSIgIlJlcG9ydCBXYXJuaW5nIgogICAgICAgICAgICAgICAgICAgICI=
MiIgIlJldHJ5IFRhc2siCiAgICAgICAgICAgICAgICAgICAgIjMiICJJZ25vcmUiCiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInBkZzo6c2NoZWR1bGVyIiAiIiB9CiAgICAgICAgICAgICA=
ICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgImxvY2FsX2VjaGFuZGxlYWxsIgo=
ICAgICAgICAgICAgICAgIGxhYmVsICAgIkhhbmRsZSBBbGwgTm9uIFplcm8iCiAgICAgICAgICAgICAgICB0eXBlICAgIHRvZ2dsZQogICAgICAgICAgICAgICAgZGVmYXVsdCB7ICIxIiB9CiAgICAgICAgICAgICAgICBwYXI=
bXRhZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICA=
ICAgICAgICAgICAgICBuYW1lICAgICJsb2NhbF9lY2N1c3RvbWNvZGUiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJFeGl0IENvZGUiCiAgICAgICAgICAgICAgICB0eXBlICAgIGludGVnZXIKICAgICAgICAgICAgICAgIGQ=
ZWZhdWx0IHsgIjEiIH0KICAgICAgICAgICAgICAgIGRpc2FibGV3aGVuICJ7IGxvY2FsX2VjaGFuZGxlYWxsICE9IDAgfSIKICAgICAgICAgICAgICAgIHJhbmdlICAgeyAxIDI1NSB9CiAgICAgICAgICAgICAgICBwYXJtdGE=
ZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBwYXJtIHsKICAgICA=
ICAgICAgICAgICBuYW1lICAgICJzZXBwYXJtIgogICAgICAgICAgICAgICAgbGFiZWwgICAiU2VwYXJhdG9yIgogICAgICAgICAgICAgICAgdHlwZSAgICBzZXBhcmF0b3IKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiIiA=
fQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWxfbWF4aW11bXJldHJpZXMiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJNYXhpbXVtIFJldHJpZXMiCiAgICA=
ICAgICAgICAgICAgdHlwZSAgICBpbnRlZ2VyCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjMiIH0KICAgICAgICAgICAgICAgIGRpc2FibGV3aGVuICJ7IGxvY2FsX2VjaGFuZGxlYnkgIT0gMiB9IgogICAgICAgICAgICA=
ICAgIHJhbmdlICAgeyAwIDEwIH0KICAgICAgICAgICAgICAgIHBhcm10YWcgeyAicGRnOjpzY2hlZHVsZXIiICIiIH0KICAgICAgICAgICAgICAgIHBhcm10YWcgeyAic2NyaXB0X2NhbGxiYWNrX2xhbmd1YWdlIiAicHl0aG8=
biIgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWxfYWRkZmFpbGNvdW50YXR0ciIKICAgICAgICAgICAgICAgIGxhYmVsICAgIlJldHJ5IENvdW50IEF0dHI=
aWJ1dGUiCiAgICAgICAgICAgICAgICB0eXBlICAgIHRvZ2dsZQogICAgICAgICAgICAgICAgam9pbm5leHQKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiMCIgfQogICAgICAgICAgICAgICAgZGlzYWJsZXdoZW4gInsgbG8=
Y2FsX2VjaGFuZGxlYnkgIT0gMiB9IgogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXQ=
aG9uIiB9CiAgICAgICAgICAgIH0KICAgICAgICAgICAgcGFybSB7CiAgICAgICAgICAgICAgICBuYW1lICAgICJsb2NhbF9mYWlsY291bnRhdHRyIgogICAgICAgICAgICAgICAgbGFiZWwgICAibG9jYWxfZmFpbGNvdW50YXQ=
dHIiCiAgICAgICAgICAgICAgICB0eXBlICAgIHN0cmluZwogICAgICAgICAgICAgICAgbm9sYWJlbAogICAgICAgICAgICAgICAgZGVmYXVsdCB7ICJmYWlsdXJlY291bnQiIH0KICAgICAgICAgICAgICAgIGRpc2FibGV3aGU=
biAieyBsb2NhbF9hZGRmYWlsY291bnRhdHRyID09IDAgfSB7IGxvY2FsX2VjaGFuZGxlYnkgIT0gMiB9IgogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICAgICAgcGE=
cm10YWcgeyAic2NyaXB0X2NhbGxiYWNrX2xhbmd1YWdlIiAicHl0aG9uIiB9CiAgICAgICAgICAgIH0KICAgICAgICB9CgogICAgICAgIGdyb3Vwc2ltcGxlIHsKICAgICAgICAgICAgbmFtZSAgICAiZm9sZGVyMyIKICAgICA=
ICAgICAgIGxhYmVsICAgIlRhc2sgRW52aXJvbm1lbnQiCgogICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgImxvY2FsX3VzZWhvdWRpbmltYXh0aHJlYWRzIgogICAgICAgICAgICAgICAgbGFiZWw=
ICAgImxvY2FsX3VzZWhvdWRpbmltYXh0aHJlYWRzIgogICAgICAgICAgICAgICAgdHlwZSAgICB0b2dnbGUKICAgICAgICAgICAgICAgIG5vbGFiZWwKICAgICAgICAgICAgICAgIGpvaW5uZXh0CiAgICAgICAgICAgICAgICA=
ZGVmYXVsdCB7ICIwIiB9CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInBkZzo6c2NoZWR1bGVyIiAiIiB9CiAgICAgICAgICAgIH0KICAgICAgICAgICAgcGFybSB7CiAgICAgICAgICAgICAgICBuYW1lICAgICJsb2NhbF8=
aG91ZGluaW1heHRocmVhZHMiCiAgICAgICAgICAgICAgICBsYWJlbCAgICJIb3VkaW5pIE1heCBUaHJlYWRzIgogICAgICAgICAgICAgICAgdHlwZSAgICBpbnRlZ2VyCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjAiIH0=
CiAgICAgICAgICAgICAgICBkaXNhYmxld2hlbiAieyBsb2NhbF91c2Vob3VkaW5pbWF4dGhyZWFkcyA9PSAwIH0iCiAgICAgICAgICAgICAgICByYW5nZSAgIHsgMCAxMCB9CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInA=
ZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWxfcmVxdWlyZXN3aW5kb3ciCiAgICAgICAgICAgICAgICBsYWJlbCAgICJSZXE=
dWlyZXMgR1VJIFdpbmRvdyIKICAgICAgICAgICAgICAgIHR5cGUgICAgdG9nZ2xlCiAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIjAiIH0KICAgICAgICAgICAgICAgIHBhcm10YWcgeyAicGRnOjpzY2hlZHVsZXIiICIiIH0=
CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInNjcmlwdF9jYWxsYmFja19sYW5ndWFnZSIgInB5dGhvbiIgfQogICAgICAgICAgICB9CiAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgbmFtZSAgICAibG9jYWw=
X2VudnVuc2V0IgogICAgICAgICAgICAgICAgbGFiZWwgICAiVW5zZXQgVmFyaWFibGVzIgogICAgICAgICAgICAgICAgdHlwZSAgICBzdHJpbmcKICAgICAgICAgICAgICAgIGRlZmF1bHQgeyAiIiB9CiAgICAgICAgICAgICA=
ICAgcGFybXRhZyB7ICJwZGc6OnNjaGVkdWxlciIgIiIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJweXRob24iIH0KICAgICAgICAgICAgfQogICAgICAgICAgICBtdWw=
dGlwYXJtIHsKICAgICAgICAgICAgICAgIG5hbWUgICAgImxvY2FsX2Vudm11bHRpIgogICAgICAgICAgICAgICAgbGFiZWwgICAgIkVudmlyb25tZW50IFZhcmlhYmxlcyIKICAgICAgICAgICAgICAgIHBhcm10YWcgeyAicGQ=
Zzo6bm9jb3B5IiAiIiB9CiAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInNjcmlwdF9jYWxsYmFjayIgIiIgfQogICAgICAgICAgICAgICAgcGFybXRhZyB7ICJzY3JpcHRfY2FsbGJhY2tfbGFuZ3VhZ2UiICJoc2NyaXB0IiA=
fQoKICAgICAgICAgICAgICAgIHBhcm0gewogICAgICAgICAgICAgICAgICAgIG5hbWUgICAgImxvY2FsX2Vudm5hbWUjIgogICAgICAgICAgICAgICAgICAgIGxhYmVsICAgIk5hbWUiCiAgICAgICAgICAgICAgICAgICAgdHk=
cGUgICAgc3RyaW5nCiAgICAgICAgICAgICAgICAgICAgam9pbm5leHQKICAgICAgICAgICAgICAgICAgICBkZWZhdWx0IHsgIiIgfQogICAgICAgICAgICAgICAgICAgIHBhcm10YWcgeyAicGRnOjpzY2hlZHVsZXIiICIiIH0=
CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICBwYXJtIHsKICAgICAgICAgICAgICAgICAgICBuYW1lICAgICJsb2NhbF9lbnZ2YWx1ZSMiCiAgICAgICAgICAgICAgICAgICAgbGFiZWwgICAiVmFsdWUiCiAgICA=
ICAgICAgICAgICAgICAgIHR5cGUgICAgc3RyaW5nCiAgICAgICAgICAgICAgICAgICAgZGVmYXVsdCB7ICIiIH0KICAgICAgICAgICAgICAgICAgICBwYXJtdGFnIHsgInBkZzo6c2NoZWR1bGVyIiAiIiB9CiAgICAgICAgICA=
ICAgICAgfQogICAgICAgICAgICB9CgogICAgICAgIH0KCiAgICB9Cgp9Cg==

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="expression.func"
Content-Type: text/plain

# 0 bytes

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="vex.def"
Content-Type: text/plain

comment ""
position 0 6
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed off
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718792
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="vex.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="vex.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="mat.def"
Content-Type: text/plain

comment ""
position 0 3.75
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718792
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="mat.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="mat.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj.def"
Content-Type: text/plain

comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render on highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718790
  modify 1614724720
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.init"
Content-Type: text/plain

type = geo
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.def"
Content-Type: text/plain

objflags objflags =  origin off
pretransform UT_DMatrix4 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
comment ""
position -2.61129 0.455565
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render off highlight off unload off savedata off compress on colordefault on exposed on selectable on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718856
  modify 1614722766
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.spareparmdef"
Content-Type: text/plain

    group {
        name    "stdswitcher4"
        label   "Transform"

        parm {
            name    "xOrd"
            baseparm
            label   "Transform Order"
            joinnext
            export  none
        }
        parm {
            name    "rOrd"
            baseparm
            label   "Rotate Order"
            nolabel
            export  none
        }
        parm {
            name    "t"
            baseparm
            label   "Translate"
            export  all
        }
        parm {
            name    "r"
            baseparm
            label   "Rotate"
            export  all
        }
        parm {
            name    "s"
            baseparm
            label   "Scale"
            export  none
        }
        parm {
            name    "p"
            baseparm
            label   "Pivot Translate"
            export  none
        }
        parm {
            name    "pr"
            baseparm
            label   "Pivot Rotate"
            export  none
        }
        parm {
            name    "scale"
            baseparm
            label   "Uniform Scale"
            export  none
        }
        parm {
            name    "pre_xform"
            baseparm
            label   "Modify Pre-Transform"
            export  none
        }
        parm {
            name    "keeppos"
            baseparm
            label   "Keep Position When Parenting"
            export  none
        }
        parm {
            name    "childcomp"
            baseparm
            label   "Child Compensation"
            export  none
        }
        parm {
            name    "constraints_on"
            baseparm
            label   "Enable Constraints"
            export  none
        }
        parm {
            name    "constraints_path"
            baseparm
            label   "Constraints"
            export  none
        }
        parm {
            name    "lookatpath"
            baseparm
            label   "Look At"
            invisible
            export  none
        }
        parm {
            name    "lookupobjpath"
            baseparm
            label   "Look Up Object"
            invisible
            export  none
        }
        parm {
            name    "lookup"
            baseparm
            label   "Look At Up Vector"
            invisible
            export  none
        }
        parm {
            name    "pathobjpath"
            baseparm
            label   "Path Object"
            invisible
            export  none
        }
        parm {
            name    "roll"
            baseparm
            label   "Roll"
            invisible
            export  none
        }
        parm {
            name    "pos"
            baseparm
            label   "Position"
            invisible
            export  none
        }
        parm {
            name    "uparmtype"
            baseparm
            label   "Parameterization"
            invisible
            export  none
        }
        parm {
            name    "pathorient"
            baseparm
            label   "Orient Along Path"
            invisible
            export  none
        }
        parm {
            name    "up"
            baseparm
            label   "Orient Up Vector"
            invisible
            export  none
        }
        parm {
            name    "bank"
            baseparm
            label   "Auto-Bank factor"
            invisible
            export  none
        }
    }

    group {
        name    "stdswitcher4_1"
        label   "Render"

        parm {
            name    "shop_materialpath"
            baseparm
            label   "Material"
            export  none
        }
        parm {
            name    "shop_materialopts"
            baseparm
            label   "Options"
            invisible
            export  none
        }
        parm {
            name    "tdisplay"
            baseparm
            label   "Display"
            joinnext
            export  none
        }
        parm {
            name    "display"
            baseparm
            label   "Display"
            export  none
        }
        parm {
            name    "viewportlod"
            label   "Display As"
            type    ordinal
            default { "full" }
            help    "Choose how the object's geometry should be rendered in the viewport"
            menu {
                "full"      "Full Geometry"
                "points"    "Point Cloud"
                "box"       "Bounding Box"
                "centroid"  "Centroid"
                "hidden"    "Hidden"
                "subd"      "Subdivision Surface / Curves"
            }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendervisibility"
            label   "Render Visibility"
            type    string
            default { "*" }
            menureplace {
                "*"                             "Visible to all"
                "primary"                       "Visible only to primary rays"
                "primary|shadow"                "Visible only to primary and shadow rays"
                "-primary"                      "Invisible to primary rays (Phantom)"
                "-diffuse"                      "Invisible to diffuse rays"
                "-diffuse&-reflect&-refract"    "Invisible to secondary rays"
                ""                              "Invisible (Unrenderable)"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendervisibility" }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendersubd"
            label   "Render Polygons As Subdivision (Mantra)"
            type    toggle
            default { "0" }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendersubd" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdstyle"
            label   "Subdivision Style"
            type    string
            default { "mantra_catclark" }
            hidewhen "{ vm_rendersubd == 0 }"
            menu {
                "mantra_catclark"   "Mantra Catmull-Clark"
                "osd_catclark"      "OpenSubdiv Catmull-Clark"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdstyle" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdgroup"
            label   "Subdivision Group"
            type    string
            default { "" }
            hidewhen "{ vm_rendersubd == 0 }"
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdgroup" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_quality"
            label   "Open Subdiv Quality"
            type    float
            default { "1" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_quality" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_vtxinterp"
            label   "OSD Vtx Interp"
            type    integer
            default { "2" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "No vertex interpolation"
                "1" "Edges only"
                "2" "Edges and Corners"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_vtxinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_fvarinterp"
            label   "OSD FVar Interp"
            type    integer
            default { "4" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "Smooth everywhere"
                "1" "Sharpen corners only"
                "2" "Sharpen edges and corners"
                "3" "Sharpen edges and propagated corners"
                "4" "Sharpen all boundaries"
                "5" "Bilinear interpolation"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_fvarinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        group {
            name    "folder0"
            label   "Shading"

            parm {
                name    "categories"
                label   "Categories"
                type    string
                default { "" }
                help    "A list of tags which can be used to select the object"
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "reflectmask"
                label   "Reflection Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be reflected on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "refractmask"
                label   "Refraction Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be refracted on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightmask"
                label   "Light Mask"
                type    oplist
                default { "*" }
                help    "Lights that illuminate this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/LIGHT!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightcategories"
                label   "Light Selection"
                type    string
                default { "*" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_lpetag"
                label   "LPE Tag"
                type    string
                default { "" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "lpetag" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilter"
                label   "Volume Filter"
                type    string
                default { "box" }
                menu {
                    "box"       "Box Filter"
                    "gaussian"  "Gaussian"
                    "bartlett"  "Bartlett (triangle)"
                    "catrom"    "Catmull-Rom"
                    "hanning"   "Hanning"
                    "blackman"  "Blackman"
                    "sinc"      "Sinc (sharpening)"
                }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filter" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilterwidth"
                label   "Volume Filter Width"
                type    float
                default { "1" }
                range   { 0.001 5 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filterwidth" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_matte"
                label   "Matte shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "matte" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_rayshade"
                label   "Raytrace Shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rayshade" }
                parmtag { "spare_category" "Shading" }
            }
        }

        group {
            name    "folder0_1"
            label   "Sampling"

            parm {
                name    "geo_velocityblur"
                label   "Geometry Velocity Blur"
                type    ordinal
                default { "off" }
                disablewhen "{ allowmotionblur == 0 }"
                menu {
                    "off"       "No Velocity Blur"
                    "on"        "Velocity Blur"
                    "accelblur" "Acceleration Blur"
                }
            }
            parm {
                name    "geo_accelattribute"
                label   "Acceleration Attribute"
                type    string
                default { "accel" }
                hidewhen "{ geo_velocityblur != accelblur }"
                parmtag { "spare_category" "Sampling" }
            }
        }

        group {
            name    "folder0_2"
            label   "Dicing"

            parm {
                name    "vm_shadingquality"
                label   "Shading Quality"
                type    float
                default { "1" }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "shadingquality" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_flatness"
                label   "Dicing Flatness"
                type    float
                default { "0.05" }
                range   { 0 1 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "flatness" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_raypredice"
                label   "Ray Predicing"
                type    integer
                default { "0" }
                menu {
                    "0" "Disable Predicing"
                    "1" "Full Predicing"
                    "2" "Precompute Bounds"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "raypredice" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_curvesurface"
                label   "Shade Curves As Surfaces"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "curvesurface" }
                parmtag { "spare_category" "Dicing" }
            }
        }

        group {
            name    "folder0_3"
            label   "Geometry"

            parm {
                name    "vm_rmbackface"
                label   "Backface Removal"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rmbackface" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "shop_geometrypath"
                label   "Procedural Shader"
                type    oppath
                default { "" }
                parmtag { "opfilter" "!!SHOP/GEOMETRY!!" }
                parmtag { "oprelative" "." }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_forcegeometry"
                label   "Force Procedural Geometry Output"
                type    toggle
                default { "1" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_rendersubdcurves"
                label   "Render Polygon Curves As Subdivision (Mantra)"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rendersubdcurves" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpoints"
                label   "Render As Points (Mantra)"
                type    integer
                default { "2" }
                menu {
                    "0" "No Point Rendering"
                    "1" "Render Only Points"
                    "2" "Render Unconnected Points"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpointsas"
                label   "Render Points As (Mantra)"
                type    integer
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                menu {
                    "0" "Spheres"
                    "1" "Circles"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpointsas" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_usenforpoints"
                label   "Use N For Point Rendering"
                type    toggle
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "usenforpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pointscale"
                label   "Point Scale"
                type    float
                default { "1" }
                disablewhen "{ vm_renderpoints == 0 }"
                range   { 0! 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pointscale" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pscalediameter"
                label   "Treat Point Scale as Diameter Instead of Radius"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pscalediameter" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_metavolume"
                label   "Metaballs as Volume"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "metavolume" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_coving"
                label   "Coving"
                type    integer
                default { "1" }
                menu {
                    "0" "Disable Coving"
                    "1" "Coving for displacement/sub-d"
                    "2" "Coving for all primitives"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "coving" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_materialoverride"
                label   "Material Override"
                type    string
                default { "compact" }
                menu {
                    "none"      "Disabled"
                    "full"      "Evaluate for Each Primitve/Point"
                    "compact"   "Evaluate Once"
                }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_overridedetail"
                label   "Ignore Geometry Attribute Shaders"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "overridedetail" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_procuseroottransform"
                label   "Proc Use Root Transform"
                type    toggle
                default { "1" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "procuseroottransform" }
                parmtag { "spare_category" "Geometry" }
            }
        }

    }

    group {
        name    "stdswitcher4_2"
        label   "Misc"

        parm {
            name    "use_dcolor"
            baseparm
            label   "Set Wireframe Color"
            export  none
        }
        parm {
            name    "dcolor"
            baseparm
            label   "Wireframe Color"
            export  none
        }
        parm {
            name    "picking"
            baseparm
            label   "Viewport Selecting Enabled"
            export  none
        }
        parm {
            name    "pickscript"
            baseparm
            label   "Select Script"
            export  none
        }
        parm {
            name    "caching"
            baseparm
            label   "Cache Object Transform"
            export  none
        }
        parm {
            name    "vport_shadeopen"
            baseparm
            label   "Shade Open Curves In Viewport"
            export  none
        }
        parm {
            name    "vport_displayassubdiv"
            baseparm
            label   "Display as Subdivision in Viewport"
            invisible
            export  none
        }
        parm {
            name    "vport_onionskin"
            baseparm
            label   "Onion Skinning"
            export  none
        }
    }


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.parm"
Content-Type: text/plain

{
version 0.8
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xOrd	[ 0	locks=0 ]	(	"srt"	)
rOrd	[ 0	locks=0 ]	(	"xyz"	)
t	[ 0	locks=0 ]	(	0	0	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
s	[ 0	locks=0 ]	(	1	1	1	)
p	[ 0	locks=0 ]	(	0	0	0	)
pr	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	)
pre_xform	[ 0	locks=0 ]	(	0	)
keeppos	[ 0	locks=0 ]	(	"off"	)
childcomp	[ 0	locks=0 ]	(	"off"	)
constraints_on	[ 0	locks=0 ]	(	"off"	)
constraints_path	[ 0	locks=0 ]	(	""	)
lookatpath	[ 0	locks=0 ]	(	""	)
lookupobjpath	[ 0	locks=0 ]	(	""	)
lookup	[ 0	locks=0 ]	(	on	)
pathobjpath	[ 0	locks=0 ]	(	""	)
roll	[ 0	locks=0 ]	(	0	)
pos	[ 0	locks=0 ]	(	0	)
uparmtype	[ 0	locks=0 ]	(	"arc"	)
pathorient	[ 0	locks=0 ]	(	1	)
up	[ 0	locks=0 ]	(	0	1	0	)
bank	[ 0	locks=0 ]	(	0	)
shop_materialpath	[ 0	locks=0 ]	(	""	)
shop_materialopts	[ 0	locks=0 ]	(	0	)
tdisplay	[ 0	locks=0 ]	(	"off"	)
display	[ 0	locks=0 ]	(	1	)
use_dcolor	[ 0	locks=0 ]	(	"off"	)
dcolor	[ 0	locks=0 ]	(	1	1	1	)
picking	[ 0	locks=0 ]	(	"on"	)
pickscript	[ 0	locks=0 ]	(	""	)
caching	[ 0	locks=0 ]	(	"on"	)
vport_shadeopen	[ 0	locks=0 ]	(	"off"	)
vport_displayassubdiv	[ 0	locks=0 ]	(	"off"	)
vport_onionskin	[ 0	locks=0 ]	(	"off"	)
stdswitcher4	[ 0	locks=0 ]	(	0	0	0	)
viewportlod	[ 0	locks=0 ]	(	"full"	)
vm_rendervisibility	[ 0	locks=0 ]	(	*	)
vm_rendersubd	[ 0	locks=0 ]	(	"off"	)
vm_subdstyle	[ 0	locks=0 ]	(	mantra_catclark	)
vm_subdgroup	[ 0	locks=0 ]	(	""	)
vm_osd_quality	[ 0	locks=0 ]	(	1	)
vm_osd_vtxinterp	[ 0	locks=0 ]	(	2	)
vm_osd_fvarinterp	[ 0	locks=0 ]	(	4	)
folder0	[ 0	locks=0 ]	(	0	0	0	0	)
categories	[ 0	locks=0 ]	(	""	)
reflectmask	[ 0	locks=0 ]	(	*	)
refractmask	[ 0	locks=0 ]	(	*	)
lightmask	[ 0	locks=0 ]	(	*	)
lightcategories	[ 0	locks=0 ]	(	*	)
vm_lpetag	[ 0	locks=0 ]	(	""	)
vm_volumefilter	[ 0	locks=0 ]	(	box	)
vm_volumefilterwidth	[ 0	locks=0 ]	(	1	)
vm_matte	[ 0	locks=0 ]	(	"off"	)
vm_rayshade	[ 0	locks=0 ]	(	"off"	)
geo_velocityblur	[ 0	locks=0 ]	(	"off"	)
geo_accelattribute	[ 0	locks=0 ]	(	accel	)
vm_shadingquality	[ 0	locks=0 ]	(	1	)
vm_flatness	[ 0	locks=0 ]	(	0.050000000000000003	)
vm_raypredice	[ 0	locks=0 ]	(	0	)
vm_curvesurface	[ 0	locks=0 ]	(	"off"	)
vm_rmbackface	[ 0	locks=0 ]	(	"off"	)
shop_geometrypath	[ 0	locks=0 ]	(	""	)
vm_forcegeometry	[ 0	locks=0 ]	(	"on"	)
vm_rendersubdcurves	[ 0	locks=0 ]	(	"off"	)
vm_renderpoints	[ 0	locks=0 ]	(	2	)
vm_renderpointsas	[ 0	locks=0 ]	(	0	)
vm_usenforpoints	[ 0	locks=0 ]	(	"off"	)
vm_pointscale	[ 0	locks=0 ]	(	1	)
vm_pscalediameter	[ 0	locks=0 ]	(	"off"	)
vm_metavolume	[ 0	locks=0 ]	(	"off"	)
vm_coving	[ 0	locks=0 ]	(	1	)
vm_materialoverride	[ 0	locks=0 ]	(	compact	)
vm_overridedetail	[ 0	locks=0 ]	(	"off"	)
vm_procuseroottransform	[ 0	locks=0 ]	(	"on"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/box1.init"
Content-Type: text/plain

type = box
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/box1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position 0 0
connectornextid 1
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
0 "output1"
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718856
  modify 1614721756
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/box1.parm"
Content-Type: text/plain

{
version 0.8
type	[ 0	locks=0 ]	(	"poly"	)
surftype	[ 0	locks=0 ]	(	"quads"	)
consolidatepts	[ 0	locks=0 ]	(	"on"	)
size	[ 0	locks=0 ]	(	1	1	1	)
t	[ 0	locks=0 ]	(	0	0	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	)
divrate	[ 0	locks=0 ]	(	4	4	4	)
orderrate	[ 0	locks=0 ]	(	4	4	4	)
dodivs	[ 0	locks=0 ]	(	"off"	)
divs	[ 0	locks=0 ]	(	3	3	3	)
rebar	[ 0	locks=0 ]	(	"off"	)
orientedbbox	[ 0	locks=0 ]	(	"off"	)
vertexnormals	[ 0	locks=0 ]	(	"off"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/box1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude1.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -3.81639e-17 -0.973509
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	box1 0 1 "input1"
}
inputs
{
0 	box1 0 1
}
stat
{
  create 1614721751
  modify 1614721816
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude1.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude2.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude2.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -1.73472e-17 -1.70936
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude1 1 1 "input1"
}
inputs
{
0 	polyextrude1 0 1
}
stat
{
  create 1614721751
  modify 1614721818
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude2.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude2.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude3.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude3.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -1.73472e-17 -2.60558
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude2 1 1 "input1"
}
inputs
{
0 	polyextrude2 0 1
}
stat
{
  create 1614721751
  modify 1614721829
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude3.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude3.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude4.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude4.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -5.55112e-17 -5.08034
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude5 1 1 "input1"
}
inputs
{
0 	polyextrude5 0 1
}
stat
{
  create 1614721751
  modify 1614722736
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude4.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude4.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude5.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude5.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -5.55112e-17 -4.18412
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude6 1 1 "input1"
}
inputs
{
0 	polyextrude6 0 1
}
stat
{
  create 1614721751
  modify 1614721821
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude5.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude5.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude6.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude6.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -5.55112e-17 -3.44827
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude3 1 1 "input1"
}
inputs
{
0 	polyextrude3 0 1
}
stat
{
  create 1614721751
  modify 1614721820
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude6.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.44600000000000001	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude6.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/file1.init"
Content-Type: text/plain

type = file
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/file1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position 5.44906 -1.47851
connectornextid 1
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
0 "output1"
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614721953
  modify 1614722649
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.9 0.8 0.55 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/file1.chn"
Content-Type: text/plain

{
    channel index {
      lefttype = extend
      righttype = extend
      flags = 0
      segment { length = 0 expr = $FF-ch(\"f1\") }
    }
  }

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/file1.parm"
Content-Type: text/plain

{
version 0.8
filemode	[ 0	locks=0 ]	(	"read"	)
file	[ 0	locks=0 ]	(	"$HIP/01. INPUT GEO/Brocolli/1/model.obj"	)
reload	[ 0	locks=0 ]	(	0	)
objpattern	[ 0	locks=0 ]	(	*	)
geodatapath	[ 0	locks=0 ]	(	""	)
missingframe	[ 0	locks=0 ]	(	"error"	)
loadtype	[ 0	locks=0 ]	(	"full"	)
packedviewedit	[ 0	locks=0 ]	(	"unchanged"	)
viewportlod	[ 0	locks=0 ]	(	"box"	)
packexpanded	[ 0	locks=0 ]	(	"on"	)
delayload	[ 0	locks=0 ]	(	"off"	)
mkpath	[ 0	locks=0 ]	(	"on"	)
cachesize	[ 0	locks=0 ]	(	0	)
prefetch	[ 0	locks=0 ]	(	"off"	)
f	[ 0	locks=0 ]	(	1	24	)
index	[ 0	locks=0 ]	(	[ index	0 ] 	)
wrap	[ 0	locks=0 ]	(	"cycle"	)
retry	[ 0	locks=0 ]	(	0	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/file1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/transform1.init"
Content-Type: text/plain

type = xform
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/transform1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position 5.44906 -3.33735
connectornextid 1
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
0 	file1 0 1 "input1"
}
inputs
{
0 	file1 0 1
}
stat
{
  create 1614722655
  modify 1614722712
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/transform1.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
grouptype	[ 0	locks=0 ]	(	"guess"	)
xOrd	[ 0	locks=0 ]	(	"srt"	)
rOrd	[ 0	locks=0 ]	(	"xyz"	)
t	[ 0	locks=0 ]	(	0	0	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
s	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	100	)
parmgroup_pivotxform	[ 0	locks=0 ]	(	0	)
p	[ 0	locks=0 ]	(	0	0	0	)
pr	[ 0	locks=0 ]	(	0	0	0	)
parmgroup_prexform	[ 0	locks=0 ]	(	0	)
prexform_xOrd	[ 0	locks=0 ]	(	"srt"	)
prexform_rOrd	[ 0	locks=0 ]	(	"xyz"	)
prexform_t	[ 0	locks=0 ]	(	0	0	0	)
prexform_r	[ 0	locks=0 ]	(	0	0	0	)
prexform_s	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
movecentroid	[ 0	locks=0 ]	(	0	)
attribs	[ 0	locks=0 ]	(	*	)
updatenmls	[ 0	locks=0 ]	(	"off"	)
updateaffectednmls	[ 0	locks=0 ]	(	"on"	)
vlength	[ 0	locks=0 ]	(	"on"	)
invertxform	[ 0	locks=0 ]	(	"off"	)
addattrib	[ 0	locks=0 ]	(	"off"	)
outputattrib	[ 0	locks=0 ]	(	xform	)
outputmerge	[ 0	locks=0 ]	(	"post"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/transform1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude7.init"
Content-Type: text/plain

type = polyextrude::2.0
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude7.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position -0.485866 -6.47672
connectornextid 2
flags =  lock off model off template off footprint off xray off bypass off display on render on highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
1 "output1"
}
inputsNamed3
{
0 	polyextrude4 1 1 "input1"
}
inputs
{
0 	polyextrude4 0 1
}
stat
{
  create 1614721751
  modify 1614722749
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude7.parm"
Content-Type: text/plain

{
version 0.8
group	[ 0	locks=0 ]	(	""	)
splittype	[ 0	locks=0 ]	(	"elements"	)
usesplitgroup	[ 0	locks=0 ]	(	"off"	)
splitgroup	[ 0	locks=0 ]	(	""	)
extrusionmode	[ 0	locks=0 ]	(	"primnormal"	)
ptnormalsrc	[ 0	locks=0 ]	(	"precompute"	)
ptnormalattrib	[ 0	locks=0 ]	(	N	)
dist	[ 0	locks=0 ]	(	0.153	)
inset	[ 0	locks=0 ]	(	0	)
twist	[ 0	locks=0 ]	(	0	)
divs	[ 0	locks=0 ]	(	1	)
spinetype	[ 0	locks=0 ]	(	"straight"	)
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xformsection	[ 0	locks=0 ]	(	0	)
xformfront	[ 0	locks=0 ]	(	"off"	)
xformspace	[ 0	locks=0 ]	(	"local"	)
rst	[ 0	locks=0 ]	(	"srt"	)
xyz	[ 0	locks=0 ]	(	"xyz"	)
translate	[ 0	locks=0 ]	(	0	0	0	)
rotate	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	1	1	)
shear	[ 0	locks=0 ]	(	0	0	0	)
pivotxformsection	[ 0	locks=0 ]	(	0	)
pivot	[ 0	locks=0 ]	(	0	0	0	)
pivotrotate	[ 0	locks=0 ]	(	0	0	0	)
prexformsection	[ 0	locks=0 ]	(	0	)
prexform_rst	[ 0	locks=0 ]	(	"srt"	)
prexform_xyz	[ 0	locks=0 ]	(	"xyz"	)
prexform_translate	[ 0	locks=0 ]	(	0	0	0	)
prexform_rotate	[ 0	locks=0 ]	(	0	0	0	)
prexform_scale	[ 0	locks=0 ]	(	1	1	1	)
prexform_shear	[ 0	locks=0 ]	(	0	0	0	)
outputsection	[ 0	locks=0 ]	(	0	)
outputfront	[ 0	locks=0 ]	(	"on"	)
outputfrontgrp	[ 0	locks=0 ]	(	"off"	)
frontgrp	[ 0	locks=0 ]	(	extrudeFront	)
outputback	[ 0	locks=0 ]	(	"off"	)
outputbackgrp	[ 0	locks=0 ]	(	"off"	)
backgrp	[ 0	locks=0 ]	(	extrudeBack	)
outputside	[ 0	locks=0 ]	(	"on"	)
outputsidegrp	[ 0	locks=0 ]	(	"off"	)
sidegrp	[ 0	locks=0 ]	(	extrudeSide	)
outputfrontseamgrp	[ 0	locks=0 ]	(	"off"	)
frontseamgrp	[ 0	locks=0 ]	(	extrudeFrontSeam	)
outputbackseamgrp	[ 0	locks=0 ]	(	"off"	)
backseamgrp	[ 0	locks=0 ]	(	extrudeBackSeam	)
preservegroups	[ 0	locks=0 ]	(	"on"	)
insettingsection	[ 0	locks=0 ]	(	0	)
limitinset	[ 0	locks=0 ]	(	"on"	)
commonlimit	[ 0	locks=0 ]	(	"on"	)
normalsection	[ 0	locks=0 ]	(	0	)
addvertexnomrals	[ 0	locks=0 ]	(	"off"	)
cuspangle	[ 0	locks=0 ]	(	60	)
cuspfront	[ 0	locks=0 ]	(	"on"	)
cuspback	[ 0	locks=0 ]	(	"on"	)
uvssection	[ 0	locks=0 ]	(	0	)
genuvs	[ 0	locks=0 ]	(	"on"	)
uvstyle	[ 0	locks=0 ]	(	"proprtional"	)
uvscaling	[ 0	locks=0 ]	(	"matchuv"	)
shapecontrolsection	[ 0	locks=0 ]	(	0	)
frontmagnitude	[ 0	locks=0 ]	(	1	)
backmagnitude	[ 0	locks=0 ]	(	1	)
frontstiffness	[ 0	locks=0 ]	(	0	)
backstiffness	[ 0	locks=0 ]	(	0	)
interpolation	[ 0	locks=0 ]	(	"rotatingframe"	)
spacing	[ 0	locks=0 ]	(	"arclengthuniform"	)
externalspinesection	[ 0	locks=0 ]	(	0	)
reversespinedirection	[ 0	locks=0 ]	(	"off"	)
axialrotation	[ 0	locks=0 ]	(	0	)
frontblend	[ 0	locks=0 ]	(	0.10000000000000001	)
backblend	[ 0	locks=0 ]	(	0.10000000000000001	)
thicknesssection	[ 0	locks=0 ]	(	0	)
thicknessscale	[ 0	locks=0 ]	(	1	)
usethicknessattrib	[ 0	locks=0 ]	(	"on"	)
thicknessattrib	[ 0	locks=0 ]	(	thickness	)
usethicknessramp	[ 0	locks=0 ]	(	"on"	)
thicknessramp	[ 0	locks=0 ]	(	2	)
twistsection	[ 0	locks=0 ]	(	0	)
usetwistattrib	[ 0	locks=0 ]	(	"on"	)
twistattrib	[ 0	locks=0 ]	(	twist	)
usetwistramp	[ 0	locks=0 ]	(	"on"	)
twistramp	[ 0	locks=0 ]	(	2	)
twistscale	[ 0	locks=0 ]	(	180	)
localattribs	[ 0	locks=0 ]	(	0	)
uselocalzscaleattrib	[ 0	locks=0 ]	(	"off"	)
localzscaleattrib	[ 0	locks=0 ]	(	zscale	)
uselocalinsetscaleattrib	[ 0	locks=0 ]	(	"off"	)
localinsetscaleattrib	[ 0	locks=0 ]	(	insetscale	)
uselocaltwistattrib	[ 0	locks=0 ]	(	"off"	)
localtwistscaleattrib	[ 0	locks=0 ]	(	twistscale	)
uselocaldivsattrib	[ 0	locks=0 ]	(	"off"	)
locadivscaleattrib	[ 0	locks=0 ]	(	divsscale	)
localframeattribs	[ 0	locks=0 ]	(	0	)
uselocalxattrib	[ 0	locks=0 ]	(	"off"	)
localxattrib	[ 0	locks=0 ]	(	localx	)
uselocalzattirb	[ 0	locks=0 ]	(	"off"	)
localzattirb	[ 0	locks=0 ]	(	localz	)
uselocalctrattrib	[ 0	locks=0 ]	(	"off"	)
localctrattrib	[ 0	locks=0 ]	(	localctr	)
thicknessramp1pos	[ 0	locks=0 ]	(	0	)
thicknessramp1value	[ 0	locks=0 ]	(	1	)
thicknessramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
thicknessramp2pos	[ 0	locks=0 ]	(	1	)
thicknessramp2value	[ 0	locks=0 ]	(	1	)
thicknessramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp1pos	[ 0	locks=0 ]	(	0	)
twistramp1value	[ 0	locks=0 ]	(	0.5	)
twistramp1interp	[ 0	locks=0 ]	(	"catmull-rom"	)
twistramp2pos	[ 0	locks=0 ]	(	1	)
twistramp2value	[ 0	locks=0 ]	(	0.5	)
twistramp2interp	[ 0	locks=0 ]	(	"catmull-rom"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1/polyextrude7.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.order"
Content-Type: text/plain

10
box1
polyextrude1
polyextrude2
polyextrude3
polyextrude4
polyextrude5
polyextrude6
file1
transform1
polyextrude7

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/box1.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.init"
Content-Type: text/plain

type = geo
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.def"
Content-Type: text/plain

objflags objflags =  origin off
pretransform UT_DMatrix4 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
comment ""
position 0.923717 -0.578645
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render off highlight off unload off savedata off compress on colordefault on exposed on selectable on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614723281
  modify 1614723326
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.spareparmdef"
Content-Type: text/plain

    group {
        name    "stdswitcher4"
        label   "Transform"

        parm {
            name    "xOrd"
            baseparm
            label   "Transform Order"
            joinnext
            export  none
        }
        parm {
            name    "rOrd"
            baseparm
            label   "Rotate Order"
            nolabel
            export  none
        }
        parm {
            name    "t"
            baseparm
            label   "Translate"
            export  all
        }
        parm {
            name    "r"
            baseparm
            label   "Rotate"
            export  all
        }
        parm {
            name    "s"
            baseparm
            label   "Scale"
            export  none
        }
        parm {
            name    "p"
            baseparm
            label   "Pivot Translate"
            export  none
        }
        parm {
            name    "pr"
            baseparm
            label   "Pivot Rotate"
            export  none
        }
        parm {
            name    "scale"
            baseparm
            label   "Uniform Scale"
            export  none
        }
        parm {
            name    "pre_xform"
            baseparm
            label   "Modify Pre-Transform"
            export  none
        }
        parm {
            name    "keeppos"
            baseparm
            label   "Keep Position When Parenting"
            export  none
        }
        parm {
            name    "childcomp"
            baseparm
            label   "Child Compensation"
            export  none
        }
        parm {
            name    "constraints_on"
            baseparm
            label   "Enable Constraints"
            export  none
        }
        parm {
            name    "constraints_path"
            baseparm
            label   "Constraints"
            export  none
        }
        parm {
            name    "lookatpath"
            baseparm
            label   "Look At"
            invisible
            export  none
        }
        parm {
            name    "lookupobjpath"
            baseparm
            label   "Look Up Object"
            invisible
            export  none
        }
        parm {
            name    "lookup"
            baseparm
            label   "Look At Up Vector"
            invisible
            export  none
        }
        parm {
            name    "pathobjpath"
            baseparm
            label   "Path Object"
            invisible
            export  none
        }
        parm {
            name    "roll"
            baseparm
            label   "Roll"
            invisible
            export  none
        }
        parm {
            name    "pos"
            baseparm
            label   "Position"
            invisible
            export  none
        }
        parm {
            name    "uparmtype"
            baseparm
            label   "Parameterization"
            invisible
            export  none
        }
        parm {
            name    "pathorient"
            baseparm
            label   "Orient Along Path"
            invisible
            export  none
        }
        parm {
            name    "up"
            baseparm
            label   "Orient Up Vector"
            invisible
            export  none
        }
        parm {
            name    "bank"
            baseparm
            label   "Auto-Bank factor"
            invisible
            export  none
        }
    }

    group {
        name    "stdswitcher4_1"
        label   "Render"

        parm {
            name    "shop_materialpath"
            baseparm
            label   "Material"
            export  none
        }
        parm {
            name    "shop_materialopts"
            baseparm
            label   "Options"
            invisible
            export  none
        }
        parm {
            name    "tdisplay"
            baseparm
            label   "Display"
            joinnext
            export  none
        }
        parm {
            name    "display"
            baseparm
            label   "Display"
            export  none
        }
        parm {
            name    "viewportlod"
            label   "Display As"
            type    ordinal
            default { "full" }
            help    "Choose how the object's geometry should be rendered in the viewport"
            menu {
                "full"      "Full Geometry"
                "points"    "Point Cloud"
                "box"       "Bounding Box"
                "centroid"  "Centroid"
                "hidden"    "Hidden"
                "subd"      "Subdivision Surface / Curves"
            }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendervisibility"
            label   "Render Visibility"
            type    string
            default { "*" }
            menureplace {
                "*"                             "Visible to all"
                "primary"                       "Visible only to primary rays"
                "primary|shadow"                "Visible only to primary and shadow rays"
                "-primary"                      "Invisible to primary rays (Phantom)"
                "-diffuse"                      "Invisible to diffuse rays"
                "-diffuse&-reflect&-refract"    "Invisible to secondary rays"
                ""                              "Invisible (Unrenderable)"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendervisibility" }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendersubd"
            label   "Render Polygons As Subdivision (Mantra)"
            type    toggle
            default { "0" }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendersubd" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdstyle"
            label   "Subdivision Style"
            type    string
            default { "mantra_catclark" }
            hidewhen "{ vm_rendersubd == 0 }"
            menu {
                "mantra_catclark"   "Mantra Catmull-Clark"
                "osd_catclark"      "OpenSubdiv Catmull-Clark"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdstyle" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdgroup"
            label   "Subdivision Group"
            type    string
            default { "" }
            hidewhen "{ vm_rendersubd == 0 }"
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdgroup" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_quality"
            label   "Open Subdiv Quality"
            type    float
            default { "1" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_quality" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_vtxinterp"
            label   "OSD Vtx Interp"
            type    integer
            default { "2" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "No vertex interpolation"
                "1" "Edges only"
                "2" "Edges and Corners"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_vtxinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_fvarinterp"
            label   "OSD FVar Interp"
            type    integer
            default { "4" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "Smooth everywhere"
                "1" "Sharpen corners only"
                "2" "Sharpen edges and corners"
                "3" "Sharpen edges and propagated corners"
                "4" "Sharpen all boundaries"
                "5" "Bilinear interpolation"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_fvarinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        group {
            name    "folder0"
            label   "Shading"

            parm {
                name    "categories"
                label   "Categories"
                type    string
                default { "" }
                help    "A list of tags which can be used to select the object"
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "reflectmask"
                label   "Reflection Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be reflected on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "refractmask"
                label   "Refraction Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be refracted on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightmask"
                label   "Light Mask"
                type    oplist
                default { "*" }
                help    "Lights that illuminate this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/LIGHT!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightcategories"
                label   "Light Selection"
                type    string
                default { "*" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_lpetag"
                label   "LPE Tag"
                type    string
                default { "" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "lpetag" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilter"
                label   "Volume Filter"
                type    string
                default { "box" }
                menu {
                    "box"       "Box Filter"
                    "gaussian"  "Gaussian"
                    "bartlett"  "Bartlett (triangle)"
                    "catrom"    "Catmull-Rom"
                    "hanning"   "Hanning"
                    "blackman"  "Blackman"
                    "sinc"      "Sinc (sharpening)"
                }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filter" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilterwidth"
                label   "Volume Filter Width"
                type    float
                default { "1" }
                range   { 0.001 5 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filterwidth" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_matte"
                label   "Matte shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "matte" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_rayshade"
                label   "Raytrace Shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rayshade" }
                parmtag { "spare_category" "Shading" }
            }
        }

        group {
            name    "folder0_1"
            label   "Sampling"

            parm {
                name    "geo_velocityblur"
                label   "Geometry Velocity Blur"
                type    ordinal
                default { "off" }
                disablewhen "{ allowmotionblur == 0 }"
                menu {
                    "off"       "No Velocity Blur"
                    "on"        "Velocity Blur"
                    "accelblur" "Acceleration Blur"
                }
            }
            parm {
                name    "geo_accelattribute"
                label   "Acceleration Attribute"
                type    string
                default { "accel" }
                hidewhen "{ geo_velocityblur != accelblur }"
                parmtag { "spare_category" "Sampling" }
            }
        }

        group {
            name    "folder0_2"
            label   "Dicing"

            parm {
                name    "vm_shadingquality"
                label   "Shading Quality"
                type    float
                default { "1" }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "shadingquality" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_flatness"
                label   "Dicing Flatness"
                type    float
                default { "0.05" }
                range   { 0 1 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "flatness" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_raypredice"
                label   "Ray Predicing"
                type    integer
                default { "0" }
                menu {
                    "0" "Disable Predicing"
                    "1" "Full Predicing"
                    "2" "Precompute Bounds"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "raypredice" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_curvesurface"
                label   "Shade Curves As Surfaces"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "curvesurface" }
                parmtag { "spare_category" "Dicing" }
            }
        }

        group {
            name    "folder0_3"
            label   "Geometry"

            parm {
                name    "vm_rmbackface"
                label   "Backface Removal"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rmbackface" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "shop_geometrypath"
                label   "Procedural Shader"
                type    oppath
                default { "" }
                parmtag { "opfilter" "!!SHOP/GEOMETRY!!" }
                parmtag { "oprelative" "." }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_forcegeometry"
                label   "Force Procedural Geometry Output"
                type    toggle
                default { "1" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_rendersubdcurves"
                label   "Render Polygon Curves As Subdivision (Mantra)"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rendersubdcurves" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpoints"
                label   "Render As Points (Mantra)"
                type    integer
                default { "2" }
                menu {
                    "0" "No Point Rendering"
                    "1" "Render Only Points"
                    "2" "Render Unconnected Points"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpointsas"
                label   "Render Points As (Mantra)"
                type    integer
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                menu {
                    "0" "Spheres"
                    "1" "Circles"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpointsas" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_usenforpoints"
                label   "Use N For Point Rendering"
                type    toggle
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "usenforpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pointscale"
                label   "Point Scale"
                type    float
                default { "1" }
                disablewhen "{ vm_renderpoints == 0 }"
                range   { 0! 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pointscale" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pscalediameter"
                label   "Treat Point Scale as Diameter Instead of Radius"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pscalediameter" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_metavolume"
                label   "Metaballs as Volume"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "metavolume" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_coving"
                label   "Coving"
                type    integer
                default { "1" }
                menu {
                    "0" "Disable Coving"
                    "1" "Coving for displacement/sub-d"
                    "2" "Coving for all primitives"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "coving" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_materialoverride"
                label   "Material Override"
                type    string
                default { "compact" }
                menu {
                    "none"      "Disabled"
                    "full"      "Evaluate for Each Primitve/Point"
                    "compact"   "Evaluate Once"
                }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_overridedetail"
                label   "Ignore Geometry Attribute Shaders"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "overridedetail" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_procuseroottransform"
                label   "Proc Use Root Transform"
                type    toggle
                default { "1" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "procuseroottransform" }
                parmtag { "spare_category" "Geometry" }
            }
        }

    }

    group {
        name    "stdswitcher4_2"
        label   "Misc"

        parm {
            name    "use_dcolor"
            baseparm
            label   "Set Wireframe Color"
            export  none
        }
        parm {
            name    "dcolor"
            baseparm
            label   "Wireframe Color"
            export  none
        }
        parm {
            name    "picking"
            baseparm
            label   "Viewport Selecting Enabled"
            export  none
        }
        parm {
            name    "pickscript"
            baseparm
            label   "Select Script"
            export  none
        }
        parm {
            name    "caching"
            baseparm
            label   "Cache Object Transform"
            export  none
        }
        parm {
            name    "vport_shadeopen"
            baseparm
            label   "Shade Open Curves In Viewport"
            export  none
        }
        parm {
            name    "vport_displayassubdiv"
            baseparm
            label   "Display as Subdivision in Viewport"
            invisible
            export  none
        }
        parm {
            name    "vport_onionskin"
            baseparm
            label   "Onion Skinning"
            export  none
        }
    }


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.parm"
Content-Type: text/plain

{
version 0.8
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xOrd	[ 0	locks=0 ]	(	"srt"	)
rOrd	[ 0	locks=0 ]	(	"xyz"	)
t	[ 0	locks=0 ]	(	0	5.2999999999999998	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
s	[ 0	locks=0 ]	(	1	1	1	)
p	[ 0	locks=0 ]	(	0	0	0	)
pr	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	)
pre_xform	[ 0	locks=0 ]	(	0	)
keeppos	[ 0	locks=0 ]	(	"off"	)
childcomp	[ 0	locks=0 ]	(	"off"	)
constraints_on	[ 0	locks=0 ]	(	"off"	)
constraints_path	[ 0	locks=0 ]	(	""	)
lookatpath	[ 0	locks=0 ]	(	""	)
lookupobjpath	[ 0	locks=0 ]	(	""	)
lookup	[ 0	locks=0 ]	(	on	)
pathobjpath	[ 0	locks=0 ]	(	""	)
roll	[ 0	locks=0 ]	(	0	)
pos	[ 0	locks=0 ]	(	0	)
uparmtype	[ 0	locks=0 ]	(	"arc"	)
pathorient	[ 0	locks=0 ]	(	1	)
up	[ 0	locks=0 ]	(	0	1	0	)
bank	[ 0	locks=0 ]	(	0	)
shop_materialpath	[ 0	locks=0 ]	(	""	)
shop_materialopts	[ 0	locks=0 ]	(	0	)
tdisplay	[ 0	locks=0 ]	(	"off"	)
display	[ 0	locks=0 ]	(	1	)
use_dcolor	[ 0	locks=0 ]	(	"off"	)
dcolor	[ 0	locks=0 ]	(	1	1	1	)
picking	[ 0	locks=0 ]	(	"on"	)
pickscript	[ 0	locks=0 ]	(	""	)
caching	[ 0	locks=0 ]	(	"on"	)
vport_shadeopen	[ 0	locks=0 ]	(	"off"	)
vport_displayassubdiv	[ 0	locks=0 ]	(	"off"	)
vport_onionskin	[ 0	locks=0 ]	(	"off"	)
stdswitcher4	[ 0	locks=0 ]	(	0	0	0	)
viewportlod	[ 0	locks=0 ]	(	"full"	)
vm_rendervisibility	[ 0	locks=0 ]	(	*	)
vm_rendersubd	[ 0	locks=0 ]	(	"off"	)
vm_subdstyle	[ 0	locks=0 ]	(	mantra_catclark	)
vm_subdgroup	[ 0	locks=0 ]	(	""	)
vm_osd_quality	[ 0	locks=0 ]	(	1	)
vm_osd_vtxinterp	[ 0	locks=0 ]	(	2	)
vm_osd_fvarinterp	[ 0	locks=0 ]	(	4	)
folder0	[ 0	locks=0 ]	(	0	0	0	0	)
categories	[ 0	locks=0 ]	(	""	)
reflectmask	[ 0	locks=0 ]	(	*	)
refractmask	[ 0	locks=0 ]	(	*	)
lightmask	[ 0	locks=0 ]	(	*	)
lightcategories	[ 0	locks=0 ]	(	*	)
vm_lpetag	[ 0	locks=0 ]	(	""	)
vm_volumefilter	[ 0	locks=0 ]	(	box	)
vm_volumefilterwidth	[ 0	locks=0 ]	(	1	)
vm_matte	[ 0	locks=0 ]	(	"off"	)
vm_rayshade	[ 0	locks=0 ]	(	"off"	)
geo_velocityblur	[ 0	locks=0 ]	(	"off"	)
geo_accelattribute	[ 0	locks=0 ]	(	accel	)
vm_shadingquality	[ 0	locks=0 ]	(	1	)
vm_flatness	[ 0	locks=0 ]	(	0.050000000000000003	)
vm_raypredice	[ 0	locks=0 ]	(	0	)
vm_curvesurface	[ 0	locks=0 ]	(	"off"	)
vm_rmbackface	[ 0	locks=0 ]	(	"off"	)
shop_geometrypath	[ 0	locks=0 ]	(	""	)
vm_forcegeometry	[ 0	locks=0 ]	(	"on"	)
vm_rendersubdcurves	[ 0	locks=0 ]	(	"off"	)
vm_renderpoints	[ 0	locks=0 ]	(	2	)
vm_renderpointsas	[ 0	locks=0 ]	(	0	)
vm_usenforpoints	[ 0	locks=0 ]	(	"off"	)
vm_pointscale	[ 0	locks=0 ]	(	1	)
vm_pscalediameter	[ 0	locks=0 ]	(	"off"	)
vm_metavolume	[ 0	locks=0 ]	(	"off"	)
vm_coving	[ 0	locks=0 ]	(	1	)
vm_materialoverride	[ 0	locks=0 ]	(	compact	)
vm_overridedetail	[ 0	locks=0 ]	(	"off"	)
vm_procuseroottransform	[ 0	locks=0 ]	(	"on"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1/torus1.init"
Content-Type: text/plain

type = torus
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1/torus1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render on highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614723281
  modify 1614723296
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1/torus1.parm"
Content-Type: text/plain

{
version 0.8
stdswitcher	[ 0	locks=0 ]	(	0	0	)
type	[ 0	locks=0 ]	(	"poly"	)
surftype	[ 0	locks=0 ]	(	"quads"	)
orient	[ 0	locks=0 ]	(	"y"	)
rad	[ 0	locks=0 ]	(	1	0.5	)
t	[ 0	locks=0 ]	(	0	0	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	)
rows	[ 0	locks=0 ]	(	12	)
cols	[ 0	locks=0 ]	(	24	)
imperfect	[ 0	locks=0 ]	(	"on"	)
orderu	[ 0	locks=0 ]	(	4	)
orderv	[ 0	locks=0 ]	(	4	)
angleu	[ 0	locks=0 ]	(	0	360	)
anglev	[ 0	locks=0 ]	(	0	360	)
closeu	[ 0	locks=0 ]	(	"on"	)
closev	[ 0	locks=0 ]	(	"on"	)
capu	[ 0	locks=0 ]	(	"off"	)
capv	[ 0	locks=0 ]	(	"off"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1/torus1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/torus1.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.init"
Content-Type: text/plain

type = geo
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.def"
Content-Type: text/plain

objflags objflags =  origin off
pretransform UT_DMatrix4 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
comment ""
position -2.94834 -1.53872
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render off highlight off unload off savedata off compress on colordefault on exposed on selectable on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614724720
  modify 1614724727
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.spareparmdef"
Content-Type: text/plain

    group {
        name    "stdswitcher4"
        label   "Transform"

        parm {
            name    "xOrd"
            baseparm
            label   "Transform Order"
            joinnext
            export  none
        }
        parm {
            name    "rOrd"
            baseparm
            label   "Rotate Order"
            nolabel
            export  none
        }
        parm {
            name    "t"
            baseparm
            label   "Translate"
            export  all
        }
        parm {
            name    "r"
            baseparm
            label   "Rotate"
            export  all
        }
        parm {
            name    "s"
            baseparm
            label   "Scale"
            export  none
        }
        parm {
            name    "p"
            baseparm
            label   "Pivot Translate"
            export  none
        }
        parm {
            name    "pr"
            baseparm
            label   "Pivot Rotate"
            export  none
        }
        parm {
            name    "scale"
            baseparm
            label   "Uniform Scale"
            export  none
        }
        parm {
            name    "pre_xform"
            baseparm
            label   "Modify Pre-Transform"
            export  none
        }
        parm {
            name    "keeppos"
            baseparm
            label   "Keep Position When Parenting"
            export  none
        }
        parm {
            name    "childcomp"
            baseparm
            label   "Child Compensation"
            export  none
        }
        parm {
            name    "constraints_on"
            baseparm
            label   "Enable Constraints"
            export  none
        }
        parm {
            name    "constraints_path"
            baseparm
            label   "Constraints"
            export  none
        }
        parm {
            name    "lookatpath"
            baseparm
            label   "Look At"
            invisible
            export  none
        }
        parm {
            name    "lookupobjpath"
            baseparm
            label   "Look Up Object"
            invisible
            export  none
        }
        parm {
            name    "lookup"
            baseparm
            label   "Look At Up Vector"
            invisible
            export  none
        }
        parm {
            name    "pathobjpath"
            baseparm
            label   "Path Object"
            invisible
            export  none
        }
        parm {
            name    "roll"
            baseparm
            label   "Roll"
            invisible
            export  none
        }
        parm {
            name    "pos"
            baseparm
            label   "Position"
            invisible
            export  none
        }
        parm {
            name    "uparmtype"
            baseparm
            label   "Parameterization"
            invisible
            export  none
        }
        parm {
            name    "pathorient"
            baseparm
            label   "Orient Along Path"
            invisible
            export  none
        }
        parm {
            name    "up"
            baseparm
            label   "Orient Up Vector"
            invisible
            export  none
        }
        parm {
            name    "bank"
            baseparm
            label   "Auto-Bank factor"
            invisible
            export  none
        }
    }

    group {
        name    "stdswitcher4_1"
        label   "Render"

        parm {
            name    "shop_materialpath"
            baseparm
            label   "Material"
            export  none
        }
        parm {
            name    "shop_materialopts"
            baseparm
            label   "Options"
            invisible
            export  none
        }
        parm {
            name    "tdisplay"
            baseparm
            label   "Display"
            joinnext
            export  none
        }
        parm {
            name    "display"
            baseparm
            label   "Display"
            export  none
        }
        parm {
            name    "viewportlod"
            label   "Display As"
            type    ordinal
            default { "full" }
            help    "Choose how the object's geometry should be rendered in the viewport"
            menu {
                "full"      "Full Geometry"
                "points"    "Point Cloud"
                "box"       "Bounding Box"
                "centroid"  "Centroid"
                "hidden"    "Hidden"
                "subd"      "Subdivision Surface / Curves"
            }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendervisibility"
            label   "Render Visibility"
            type    string
            default { "*" }
            menureplace {
                "*"                             "Visible to all"
                "primary"                       "Visible only to primary rays"
                "primary|shadow"                "Visible only to primary and shadow rays"
                "-primary"                      "Invisible to primary rays (Phantom)"
                "-diffuse"                      "Invisible to diffuse rays"
                "-diffuse&-reflect&-refract"    "Invisible to secondary rays"
                ""                              "Invisible (Unrenderable)"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendervisibility" }
            parmtag { "spare_category" "Render" }
        }
        parm {
            name    "vm_rendersubd"
            label   "Render Polygons As Subdivision (Mantra)"
            type    toggle
            default { "0" }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "rendersubd" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdstyle"
            label   "Subdivision Style"
            type    string
            default { "mantra_catclark" }
            hidewhen "{ vm_rendersubd == 0 }"
            menu {
                "mantra_catclark"   "Mantra Catmull-Clark"
                "osd_catclark"      "OpenSubdiv Catmull-Clark"
            }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdstyle" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_subdgroup"
            label   "Subdivision Group"
            type    string
            default { "" }
            hidewhen "{ vm_rendersubd == 0 }"
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "subdgroup" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_quality"
            label   "Open Subdiv Quality"
            type    float
            default { "1" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_quality" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_vtxinterp"
            label   "OSD Vtx Interp"
            type    integer
            default { "2" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "No vertex interpolation"
                "1" "Edges only"
                "2" "Edges and Corners"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_vtxinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        parm {
            name    "vm_osd_fvarinterp"
            label   "OSD FVar Interp"
            type    integer
            default { "4" }
            hidewhen "{ vm_rendersubd == 0 vm_subdstyle != osd_catclark }"
            menu {
                "0" "Smooth everywhere"
                "1" "Sharpen corners only"
                "2" "Sharpen edges and corners"
                "3" "Sharpen edges and propagated corners"
                "4" "Sharpen all boundaries"
                "5" "Bilinear interpolation"
            }
            range   { 0 10 }
            parmtag { "mantra_class" "object" }
            parmtag { "mantra_name" "osd_fvarinterp" }
            parmtag { "spare_category" "Geometry" }
        }
        group {
            name    "folder0"
            label   "Shading"

            parm {
                name    "categories"
                label   "Categories"
                type    string
                default { "" }
                help    "A list of tags which can be used to select the object"
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "reflectmask"
                label   "Reflection Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be reflected on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "refractmask"
                label   "Refraction Mask"
                type    oplist
                default { "*" }
                help    "Objects that will be refracted on this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/GEOMETRY!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightmask"
                label   "Light Mask"
                type    oplist
                default { "*" }
                help    "Lights that illuminate this object."
                parmtag { "opexpand" "1" }
                parmtag { "opfilter" "!!OBJ/LIGHT!!" }
                parmtag { "oprelative" "/obj" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "lightcategories"
                label   "Light Selection"
                type    string
                default { "*" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_lpetag"
                label   "LPE Tag"
                type    string
                default { "" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "lpetag" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilter"
                label   "Volume Filter"
                type    string
                default { "box" }
                menu {
                    "box"       "Box Filter"
                    "gaussian"  "Gaussian"
                    "bartlett"  "Bartlett (triangle)"
                    "catrom"    "Catmull-Rom"
                    "hanning"   "Hanning"
                    "blackman"  "Blackman"
                    "sinc"      "Sinc (sharpening)"
                }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filter" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_volumefilterwidth"
                label   "Volume Filter Width"
                type    float
                default { "1" }
                range   { 0.001 5 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "filterwidth" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_matte"
                label   "Matte shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "matte" }
                parmtag { "spare_category" "Shading" }
            }
            parm {
                name    "vm_rayshade"
                label   "Raytrace Shading"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rayshade" }
                parmtag { "spare_category" "Shading" }
            }
        }

        group {
            name    "folder0_1"
            label   "Sampling"

            parm {
                name    "geo_velocityblur"
                label   "Geometry Velocity Blur"
                type    ordinal
                default { "off" }
                disablewhen "{ allowmotionblur == 0 }"
                menu {
                    "off"       "No Velocity Blur"
                    "on"        "Velocity Blur"
                    "accelblur" "Acceleration Blur"
                }
            }
            parm {
                name    "geo_accelattribute"
                label   "Acceleration Attribute"
                type    string
                default { "accel" }
                hidewhen "{ geo_velocityblur != accelblur }"
                parmtag { "spare_category" "Sampling" }
            }
        }

        group {
            name    "folder0_2"
            label   "Dicing"

            parm {
                name    "vm_shadingquality"
                label   "Shading Quality"
                type    float
                default { "1" }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "shadingquality" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_flatness"
                label   "Dicing Flatness"
                type    float
                default { "0.05" }
                range   { 0 1 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "flatness" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_raypredice"
                label   "Ray Predicing"
                type    integer
                default { "0" }
                menu {
                    "0" "Disable Predicing"
                    "1" "Full Predicing"
                    "2" "Precompute Bounds"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "raypredice" }
                parmtag { "spare_category" "Dicing" }
            }
            parm {
                name    "vm_curvesurface"
                label   "Shade Curves As Surfaces"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "curvesurface" }
                parmtag { "spare_category" "Dicing" }
            }
        }

        group {
            name    "folder0_3"
            label   "Geometry"

            parm {
                name    "vm_rmbackface"
                label   "Backface Removal"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rmbackface" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "shop_geometrypath"
                label   "Procedural Shader"
                type    oppath
                default { "" }
                parmtag { "opfilter" "!!SHOP/GEOMETRY!!" }
                parmtag { "oprelative" "." }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_forcegeometry"
                label   "Force Procedural Geometry Output"
                type    toggle
                default { "1" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_rendersubdcurves"
                label   "Render Polygon Curves As Subdivision (Mantra)"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "rendersubdcurves" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpoints"
                label   "Render As Points (Mantra)"
                type    integer
                default { "2" }
                menu {
                    "0" "No Point Rendering"
                    "1" "Render Only Points"
                    "2" "Render Unconnected Points"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_renderpointsas"
                label   "Render Points As (Mantra)"
                type    integer
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                menu {
                    "0" "Spheres"
                    "1" "Circles"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "renderpointsas" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_usenforpoints"
                label   "Use N For Point Rendering"
                type    toggle
                default { "0" }
                disablewhen "{ vm_renderpoints == 0 }"
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "usenforpoints" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pointscale"
                label   "Point Scale"
                type    float
                default { "1" }
                disablewhen "{ vm_renderpoints == 0 }"
                range   { 0! 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pointscale" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_pscalediameter"
                label   "Treat Point Scale as Diameter Instead of Radius"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "pscalediameter" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_metavolume"
                label   "Metaballs as Volume"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "metavolume" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_coving"
                label   "Coving"
                type    integer
                default { "1" }
                menu {
                    "0" "Disable Coving"
                    "1" "Coving for displacement/sub-d"
                    "2" "Coving for all primitives"
                }
                range   { 0 10 }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "coving" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_materialoverride"
                label   "Material Override"
                type    string
                default { "compact" }
                menu {
                    "none"      "Disabled"
                    "full"      "Evaluate for Each Primitve/Point"
                    "compact"   "Evaluate Once"
                }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_overridedetail"
                label   "Ignore Geometry Attribute Shaders"
                type    toggle
                default { "0" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "overridedetail" }
                parmtag { "spare_category" "Geometry" }
            }
            parm {
                name    "vm_procuseroottransform"
                label   "Proc Use Root Transform"
                type    toggle
                default { "1" }
                parmtag { "mantra_class" "object" }
                parmtag { "mantra_name" "procuseroottransform" }
                parmtag { "spare_category" "Geometry" }
            }
        }

    }

    group {
        name    "stdswitcher4_2"
        label   "Misc"

        parm {
            name    "use_dcolor"
            baseparm
            label   "Set Wireframe Color"
            export  none
        }
        parm {
            name    "dcolor"
            baseparm
            label   "Wireframe Color"
            export  none
        }
        parm {
            name    "picking"
            baseparm
            label   "Viewport Selecting Enabled"
            export  none
        }
        parm {
            name    "pickscript"
            baseparm
            label   "Select Script"
            export  none
        }
        parm {
            name    "caching"
            baseparm
            label   "Cache Object Transform"
            export  none
        }
        parm {
            name    "vport_shadeopen"
            baseparm
            label   "Shade Open Curves In Viewport"
            export  none
        }
        parm {
            name    "vport_displayassubdiv"
            baseparm
            label   "Display as Subdivision in Viewport"
            invisible
            export  none
        }
        parm {
            name    "vport_onionskin"
            baseparm
            label   "Onion Skinning"
            export  none
        }
    }


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.parm"
Content-Type: text/plain

{
version 0.8
stdswitcher	[ 0	locks=0 ]	(	0	0	0	)
xOrd	[ 0	locks=0 ]	(	"srt"	)
rOrd	[ 0	locks=0 ]	(	"xyz"	)
t	[ 0	locks=0 ]	(	0	0	0	)
r	[ 0	locks=0 ]	(	0	0	0	)
s	[ 0	locks=0 ]	(	1	1	1	)
p	[ 0	locks=0 ]	(	0	0	0	)
pr	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	1	)
pre_xform	[ 0	locks=0 ]	(	0	)
keeppos	[ 0	locks=0 ]	(	"off"	)
childcomp	[ 0	locks=0 ]	(	"off"	)
constraints_on	[ 0	locks=0 ]	(	"off"	)
constraints_path	[ 0	locks=0 ]	(	""	)
lookatpath	[ 0	locks=0 ]	(	""	)
lookupobjpath	[ 0	locks=0 ]	(	""	)
lookup	[ 0	locks=0 ]	(	on	)
pathobjpath	[ 0	locks=0 ]	(	""	)
roll	[ 0	locks=0 ]	(	0	)
pos	[ 0	locks=0 ]	(	0	)
uparmtype	[ 0	locks=0 ]	(	"arc"	)
pathorient	[ 0	locks=0 ]	(	1	)
up	[ 0	locks=0 ]	(	0	1	0	)
bank	[ 0	locks=0 ]	(	0	)
shop_materialpath	[ 0	locks=0 ]	(	""	)
shop_materialopts	[ 0	locks=0 ]	(	0	)
tdisplay	[ 0	locks=0 ]	(	"off"	)
display	[ 0	locks=0 ]	(	1	)
use_dcolor	[ 0	locks=0 ]	(	"off"	)
dcolor	[ 0	locks=0 ]	(	1	1	1	)
picking	[ 0	locks=0 ]	(	"on"	)
pickscript	[ 0	locks=0 ]	(	""	)
caching	[ 0	locks=0 ]	(	"on"	)
vport_shadeopen	[ 0	locks=0 ]	(	"off"	)
vport_displayassubdiv	[ 0	locks=0 ]	(	"off"	)
vport_onionskin	[ 0	locks=0 ]	(	"off"	)
stdswitcher4	[ 0	locks=0 ]	(	0	0	0	)
viewportlod	[ 0	locks=0 ]	(	"full"	)
vm_rendervisibility	[ 0	locks=0 ]	(	*	)
vm_rendersubd	[ 0	locks=0 ]	(	"off"	)
vm_subdstyle	[ 0	locks=0 ]	(	mantra_catclark	)
vm_subdgroup	[ 0	locks=0 ]	(	""	)
vm_osd_quality	[ 0	locks=0 ]	(	1	)
vm_osd_vtxinterp	[ 0	locks=0 ]	(	2	)
vm_osd_fvarinterp	[ 0	locks=0 ]	(	4	)
folder0	[ 0	locks=0 ]	(	0	0	0	0	)
categories	[ 0	locks=0 ]	(	""	)
reflectmask	[ 0	locks=0 ]	(	*	)
refractmask	[ 0	locks=0 ]	(	*	)
lightmask	[ 0	locks=0 ]	(	*	)
lightcategories	[ 0	locks=0 ]	(	*	)
vm_lpetag	[ 0	locks=0 ]	(	""	)
vm_volumefilter	[ 0	locks=0 ]	(	box	)
vm_volumefilterwidth	[ 0	locks=0 ]	(	1	)
vm_matte	[ 0	locks=0 ]	(	"off"	)
vm_rayshade	[ 0	locks=0 ]	(	"off"	)
geo_velocityblur	[ 0	locks=0 ]	(	"off"	)
geo_accelattribute	[ 0	locks=0 ]	(	accel	)
vm_shadingquality	[ 0	locks=0 ]	(	1	)
vm_flatness	[ 0	locks=0 ]	(	0.050000000000000003	)
vm_raypredice	[ 0	locks=0 ]	(	0	)
vm_curvesurface	[ 0	locks=0 ]	(	"off"	)
vm_rmbackface	[ 0	locks=0 ]	(	"off"	)
shop_geometrypath	[ 0	locks=0 ]	(	""	)
vm_forcegeometry	[ 0	locks=0 ]	(	"on"	)
vm_rendersubdcurves	[ 0	locks=0 ]	(	"off"	)
vm_renderpoints	[ 0	locks=0 ]	(	2	)
vm_renderpointsas	[ 0	locks=0 ]	(	0	)
vm_usenforpoints	[ 0	locks=0 ]	(	"off"	)
vm_pointscale	[ 0	locks=0 ]	(	1	)
vm_pscalediameter	[ 0	locks=0 ]	(	"off"	)
vm_metavolume	[ 0	locks=0 ]	(	"off"	)
vm_coving	[ 0	locks=0 ]	(	1	)
vm_materialoverride	[ 0	locks=0 ]	(	compact	)
vm_overridedetail	[ 0	locks=0 ]	(	"off"	)
vm_procuseroottransform	[ 0	locks=0 ]	(	"on"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH/sphere1.init"
Content-Type: text/plain

type = sphere
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH/sphere1.def"
Content-Type: text/plain

sopflags sopflags = 
comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render on highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614724720
  modify 1614724851
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH/sphere1.parm"
Content-Type: text/plain

{
version 0.8
type	[ 0	locks=0 ]	(	"poly"	)
surftype	[ 0	locks=0 ]	(	"quads"	)
rad	[ 0	locks=0 ]	(	1	1	1	)
t	[ 0	locks=0 ]	(	0	0	9.3000000000000007	)
r	[ 0	locks=0 ]	(	0	0	0	)
scale	[ 0	locks=0 ]	(	4.5899999999999999	)
orient	[ 0	locks=0 ]	(	"y"	)
freq	[ 0	locks=0 ]	(	10	)
rows	[ 0	locks=0 ]	(	13	)
cols	[ 0	locks=0 ]	(	24	)
orderu	[ 0	locks=0 ]	(	4	)
orderv	[ 0	locks=0 ]	(	4	)
imperfect	[ 0	locks=0 ]	(	"on"	)
upole	[ 0	locks=0 ]	(	"off"	)
accurate	[ 0	locks=0 ]	(	"on"	)
triangularpoles	[ 0	locks=0 ]	(	"on"	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH/sphere1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj/sphere_VASKOH.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj.order"
Content-Type: text/plain

3
box1
torus1
sphere_VASKOH

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="obj.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="out.def"
Content-Type: text/plain

comment ""
position 0 1.5
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718790
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="out.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="out.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="out.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="ch.def"
Content-Type: text/plain

comment ""
position 0 0.75
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718790
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="ch.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="ch.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="ch.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="shop.def"
Content-Type: text/plain

comment ""
position 0 2.25
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718790
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="shop.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="shop.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="shop.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img.def"
Content-Type: text/plain

comment ""
position 0 3
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718790
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img/comp1.init"
Content-Type: text/plain

type = img
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img/comp1.def"
Content-Type: text/plain

comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718798
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img/comp1.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img/comp1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img/comp1.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="img.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="vex.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="mat.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="stage.def"
Content-Type: text/plain

comment ""
position 0 4.5
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on debug off
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718792
  modify 1614724559
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="stage.parm"
Content-Type: text/plain

{
version 0.8
resolvercontextassetpath	[ 0	locks=0 ]	(	""	)
insertionpointdescriptor	[ 0	locks=0 ]	(	""	)
rendergallerysource	[ 0	locks=0 ]	(	$HIP/galleries/$HIPNAME.$OS/rendergallery.db	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="stage.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="stage.datablocks"
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64

AAAAAAAAAAIAFF9fb25sb2FkX18uZXhwYW5zaW9uAAlleHBhbnNpb24AAAAAAAAAFX9OU0pieysACGV4cGFuZGVkJgAxfQAUX19vbmxvYWRfXy5sb2FkbWFza3MACWxvYWRtYXNrcwAAAAAAAABnewoJInBvcHVsYXRlYWxsIjo=
dHJ1ZSwKCSJwb3B1bGF0ZXBhdGhzIjpbCgldLAoJIm11dGVsYXllcnMiOlsKCV0sCgkibG9hZGFsbCI6dHJ1ZSwKCSJsb2FkcGF0aHMiOlsKCV0KfQo=

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="stage.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks.def"
Content-Type: text/plain

comment ""
position 0 5.25
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress on colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718793
  modify 1614718847
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks.parm"
Content-Type: text/plain

{
version 0.8
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1.init"
Content-Type: text/plain

type = topnet
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1.def"
Content-Type: text/plain

comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display off render off highlight off unload off savedata off compress off colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718798
  modify 1614724556
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.8 0.8 0.8 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1.parm"
Content-Type: text/plain

{
version 0.8
cookcontrolssection	[ 0	locks=0 ]	(	0	)
generatestatic	[ 0	locks=0 ]	(	0	)
cookbutton	[ 0	locks=0 ]	(	0	)
dirtybutton	[ 0	locks=0 ]	(	0	)
cancelbutton	[ 0	locks=0 ]	(	0	)
taskgraphsection	[ 0	locks=0 ]	(	0	)
savetaskgraph	[ 0	locks=0 ]	(	0	)
loadtaskgraph	[ 0	locks=0 ]	(	0	)
taskgraphfile	[ 0	locks=0 ]	(	$HIP/$HIPNAME.taskgraph.$F.py	)
taskgraphautosave	[ 0	locks=0 ]	(	"off"	)
taskgraphsaverate	[ 0	locks=0 ]	(	10	)
schedulersection	[ 0	locks=0 ]	(	0	)
topscheduler	[ 0	locks=0 ]	(	localscheduler	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"18.5.408"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1/localscheduler.init"
Content-Type: text/plain

type = localscheduler
matchesdef = 0

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1/localscheduler.def"
Content-Type: text/plain

comment ""
position 0 0
connectornextid 0
flags =  lock off model off template off footprint off xray off bypass off display on render on highlight off unload off savedata off compress off colordefault on exposed on
outputsNamed3
{
}
inputsNamed3
{
}
inputs
{
}
stat
{
  create 1614718798
  modify 1614724556
  author hrist@MEN7ALX
  access 0777
}
color UT_Color RGB 0.478 0.478 0.478 
delscript ""
exprlanguage hscript
end

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1/localscheduler.parm"
Content-Type: text/plain

{
version 0.8
folder0	[ 0	locks=0 ]	(	0	0	)
folder4	[ 0	locks=0 ]	(	0	)
pdg_workingdir	[ 0	locks=0 ]	(	$HIP	)
pdg_mapmode	[ 0	locks=0 ]	(	"0"	)
pdg_usemapzone	[ 0	locks=0 ]	(	"off"	)
pdg_mapzone	[ 0	locks=0 ]	(	$PDG_PATHMAP_ZONE	)
socketcallbacks	[ 0	locks=0 ]	(	1	)
folder5	[ 0	locks=0 ]	(	0	)
maxprocsmenu	[ 0	locks=0 ]	(	"0"	)
maxprocs	[ 0	locks=0 ]	(	1	)
verbose	[ 0	locks=0 ]	(	"off"	)
folder1	[ 0	locks=0 ]	(	0	)
tempdirmenu	[ 0	locks=0 ]	(	"1"	)
tempdirappendpid	[ 0	locks=0 ]	(	"on"	)
tempdircustom	[ 0	locks=0 ]	(	$HOUDINI_TEMP_DIR/$HIPNAME/pdgtemp	)
folder0_2	[ 0	locks=0 ]	(	0	)
local_single	[ 0	locks=0 ]	(	"off"	)
local_is_CPU_number_set	[ 0	locks=0 ]	(	"off"	)
local_CPUs_to_use	[ 0	locks=0 ]	(	1	)
folder2	[ 0	locks=0 ]	(	0	)
local_echandleby	[ 0	locks=0 ]	(	"0"	)
local_echandleall	[ 0	locks=0 ]	(	"on"	)
local_eccustomcode	[ 0	locks=0 ]	(	1	)
sepparm	[ 0	locks=0 ]	(	)
local_maximumretries	[ 0	locks=0 ]	(	3	)
local_addfailcountattr	[ 0	locks=0 ]	(	"off"	)
local_failcountattr	[ 0	locks=0 ]	(	failurecount	)
folder3	[ 0	locks=0 ]	(	0	)
local_usehoudinimaxthreads	[ 0	locks=0 ]	(	"off"	)
local_houdinimaxthreads	[ 0	locks=0 ]	(	0	)
local_requireswindow	[ 0	locks=0 ]	(	"off"	)
local_envunset	[ 0	locks=0 ]	(	""	)
local_envmulti	[ 0	locks=0 ]	(	0	)
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1/localscheduler.userdata"
Content-Type: text/plain

{
	"___Version___":{
		"type":"string",
		"value":"1"
	}
}

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks/topnet1.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename="tasks.net"
Content-Type: text/plain

1

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".scenefilevisualizers"
Content-Type: text/plain


--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".application"
Content-Type: text/plain

networkeditor -p '{\n}\n'performance -c on -d on -f on -g off -j on -k on -m off -n on -o on -t off -v on -p on -y on -u on -e off -r absolute -R seconds -w tree panetab12
chopview -a 0 -c "" -k 1 -m 1 -b 1 -e 1 -f 0 -g 0 -H 1 -i 0 -j 1 -l 0 -n 1 -V 0 -y 0 -B 0 -s 0 -S 0.034375 -u 0 -v 0 -h -10 310 -r -1.5 1.5 Build.panetab13
imgview -p '(' none -z 1 ')' 0 -c 0 -l on -s off -i imgview2
imgdispopt -m 256 -P on -M on -A on -g 2.2 -G "* ^P ^Pz ^N ^M ^B ^V ^Af ^Nt" -B 1 -v split -V 2 2 -d h -a off -i 2 -b 0 0 0 -o "" -h on -H on -c 0.8 0.8 0.8 -C 1 1 1 -S 0.8 0.8 0.8 -R 6 -F dc -D "" -I "" -f "" -s off -r 256 256 -p on -l on -t on
imgview -z 1 -p (none) 0 -c 0 -l on -s off -i imgview2
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 1
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 2
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 3
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 4
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 5
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 6
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 7
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 8
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 9
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 10
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 11
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 12
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 13
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 14
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 15
imgview2d  -V on -L on -G on -H on -P off -m 0 -p 0 1 -b 1 1 0 -g 2.2 -d "" -c -1 -t off -i on -X on imgview2 16
imgviewtime -V on -L on -G on -H on -P off -r 24 -u fr -g 0 -f on -e on -b on -d imgview2
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 1
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 2
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 3
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 4
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 5
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 6
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 7
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 8
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 9
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 10
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 11
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 12
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 13
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 14
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 15
imgviewhist -V on -L on -G on -H on -P off -c -1 -h 0 -i on imgview2 16
viewerstow -b open -x open -l open -m hide -c hide -d open Build.panetab1.world
vieweroption -a 2 -h 0 -m 1 -r 'View: Mantra' Build.panetab1.world
viewergrouplist -g off -s 0 0 -c  on -t matchselect -m '*' -e on -p off -h on Build.panetab1.world
vieweroption -p 0 -P '+geo -cam -light -muscle -bone -null -blend -other' Build.panetab1.world
viewlayout -s 2 Build.panetab1.world
viewerinspect Build.panetab1.world mode ( objects ) object_properties ( ) prim_properties ( ) enable ( 0 ) magnify ( 1 )
viewtype -t perspective Build.panetab1.world.`vpname("Build.panetab1.world",2)`
viewtype -t ortho_top Build.panetab1.world.`vpname("Build.panetab1.world",1)`
viewtype -t ortho_front Build.panetab1.world.`vpname("Build.panetab1.world",3)`
viewtype -t ortho_right Build.panetab1.world.`vpname("Build.panetab1.world",4)`
viewname -l on -n aaaa3 Build.panetab1.world.`vpname("Build.panetab1.world",2)`
viewname -l on -n aaaa2 Build.panetab1.world.`vpname("Build.panetab1.world",1)`
viewname -l on -n aaaa1 Build.panetab1.world.`vpname("Build.panetab1.world",3)`
viewname -l on -n aaaa0 Build.panetab1.world.`vpname("Build.panetab1.world",4)`
viewname -l off -n persp1 Build.panetab1.world.`vpname("Build.panetab1.world",2)`
viewname -l off -n top1 Build.panetab1.world.`vpname("Build.panetab1.world",1)`
viewname -l off -n front1 Build.panetab1.world.`vpname("Build.panetab1.world",3)`
viewname -l off -n right1 Build.panetab1.world.`vpname("Build.panetab1.world",4)`
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique scene Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r scene selectscene Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L off -G on -B none -d uv -r unique ghostscene Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w on -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique display Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w off -s wire -F off -l on -L off -G off -B none -d uv -r unique current Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s wire -F on -l on -L off -G on -B none -d uv -r unique template Build.panetab1.world.persp1
viewdisplay -B light -b off -d off -C 2 -e 1 -F on -f off -g on -G '*' -h off -H on -j off -J off -L on -n 0.2 -o off -O on -q on -r on -s off -t on -V 2 -z off -y off -x off -X off -U 4 -Y 4 -T on -R on -i on -D on -k off Build.panetab1.world.persp1
viewdisplay -Q on -m on -v on Build.panetab1.world.persp1
viewdisplay -W  off 0 0 Build.panetab1.world.persp1
viewdisplay -c on -l1 -K on -P points -p 3 Build.panetab1.world.persp1
viewdispopts -a on -b current -c 1 -C 60  -d  on -D 1 -g on -i on -n on -N 1000000 -o off -p 10 -P off -r off -R off -S 512 -l 128 -m 0.05 -M 1024 -s on -t 0.5 -u uv -w 0.1 -W 0.9 -x on -X off Build.panetab1.world.persp1
vieweffect -a 2 -A 4 -b on -B 0 -d on -D on off -e 0.8 -E -30 -30 -100 -f 1 -F 0 -g 2.2 -G 0 -h 1 -H on -i on -I 1 -j on -J 50 -K 2 -k 1 -l '' -m on -M 512 -o off -O 3 -p off -P 3 -q 1 -Q 2 -r 1024 1024 -s 2 -t 100 -T 100 -u off -U off -v 128 128 128 -w 0.05 -W off -x 0.4 0.4 0.4 -X 0.4 0.4 0.4 -y 0.4 0.4 0.4 -Y 0.0025 0.0025 0.0025 -z 0.01 -Z 0 Build.panetab1.world.persp1
viewinfotext -m off -s off -t on Build.panetab1.world.persp1
viewlight  -a on -d on -e on -h off -l on -n 8 -s on Build.panetab1.world.persp1
viewbackground -b on -e on -q 1 -i off -m 0 0 -M 1 1 Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off persp Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off cam Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off top Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off front Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off right Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off bottom Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off back Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off left Build.panetab1.world.persp1
viewroto  -S file -F '$HH/pic/uvgrid_grey.pic' -C '' -a on -o 0 0 -s 1 1 -B 0.2 -e off uv Build.panetab1.world.persp1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off image Build.panetab1.world.persp1
viewtransform Build.panetab1.world.persp1 version ( 3 )  flag ( Fx )  orthowidth ( 0.252917 )  focal ( 50 )  aperture ( 41.4214 )  window ( 0 1 0 1 )  winroll ( 0 )  clear ( 1 )  nearfar ( 3.04676e-05 284.836 )  aspect ( 1.33333 )  pixelaspect ( 1 )  txyz ( -5.60433 -0.106002 47.6251 )  pxyz ( 0.683984 1.7631 5.01947 )  rotation ( -0.937766 -0.1401 0.317751 -6.34478e-07 0.915007 0.403436 -0.347266 0.378329 -0.858064  )  homedistance ( 0.357399 )  homeadjboxwidth ( 0.252917 )  homeorthowidth ( 0.252917 )  homeradius ( 0.284479 )  homeaxis ( 0 )  homecustom ( 0.707107 -0.353553 0.612372 0 0.866025 0.5 -0.707107 -0.353553 0.612372  )  adjustlimits ( 1 )  
viewcamera -c '' Build.panetab1.world.persp1
vieworthogrid -d off -o 0 0 0 -s 0.2 0.2 -r 5 5 -R 1 Build.panetab1.world.persp1
viewuvgrid -r on -s 0.1 0.1 -P off -S 64 64 -O 0 0 -C on -t on Build.panetab1.world.persp1
viewagentopts  -L on -b 0 -d 1 -l 0 -m 4 -p 1000 -w 1 Build.panetab1.world.persp1
viewonionskin  -e on -a 4 -b 4 -i 6 -o 0.5 -A 1 1 1 -B 1 1 1 Build.panetab1.world.persp1
viewposteffects  -D off -B off -t "" -f off -V off -S on -a 1 -b 5 -F 1 -g 1 -c 1 1 1 -C 1 1 1 -d 1e+06 -h 0 -H 100 10 -i 1 -I 1 -l 1 -n "" -o 1 -O 1 -r 0 1000 -R 1 200 -s 1 1 -u 0 -U 100 10 -v 0 Build.panetab1.world.persp1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique scene Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r scene selectscene Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L off -G on -B none -d uv -r unique ghostscene Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w on -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique display Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w off -s wire -F off -l on -L off -G off -B none -d uv -r unique current Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s wire -F on -l on -L off -G on -B none -d uv -r unique template Build.panetab1.world.top1
viewdisplay -B light -b off -d off -C 2 -e 1 -F on -f off -g on -G '*' -h off -H on -j off -J off -L on -n 0.2 -o off -O on -q on -r on -s off -t on -V 2 -z off -y off -x off -X off -U 4 -Y 4 -T on -R on -i on -D on -k off Build.panetab1.world.top1
viewdisplay -Q on -m on -v on Build.panetab1.world.top1
viewdisplay -W  off 0 0 Build.panetab1.world.top1
viewdisplay -c on -l1 -K on -P points -p 3 Build.panetab1.world.top1
viewdispopts -a on -b current -c 1 -C 60  -d  on -D 1 -g on -i on -n on -N 1000000 -o off -p 10 -P off -r off -R off -S 512 -l 128 -m 0.05 -M 1024 -s on -t 0.5 -u uv -w 0.1 -W 0.9 -x on -X off Build.panetab1.world.top1
vieweffect -a 2 -A 4 -b on -B 0 -d on -D on off -e 0.8 -E -30 -30 -100 -f 1 -F 0 -g 2.2 -G 0 -h 1 -H on -i on -I 1 -j on -J 50 -K 2 -k 1 -l '' -m on -M 512 -o off -O 3 -p off -P 3 -q 1 -Q 2 -r 1024 1024 -s 2 -t 100 -T 100 -u off -U off -v 128 128 128 -w 0.05 -W off -x 0.4 0.4 0.4 -X 0.4 0.4 0.4 -y 0.4 0.4 0.4 -Y 0.0025 0.0025 0.0025 -z 0.01 -Z 0 Build.panetab1.world.top1
viewinfotext -m off -s off -t on Build.panetab1.world.top1
viewlight  -a on -d on -e on -h off -l on -n 8 -s on Build.panetab1.world.top1
viewbackground -b on -e on -q 1 -i off -m 0 0 -M 1 1 Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off persp Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off cam Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off top Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off front Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off right Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off bottom Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off back Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off left Build.panetab1.world.top1
viewroto  -S file -F '$HH/pic/uvgrid_grey.pic' -C '' -a on -o 0 0 -s 1 1 -B 0.2 -e off uv Build.panetab1.world.top1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off image Build.panetab1.world.top1
viewtransform Build.panetab1.world.top1 version ( 3 )  flag ( Fox )  orthowidth ( 2.22222 )  focal ( 50 )  aperture ( 41.4214 )  window ( 0 1 0 1 )  winroll ( 0 )  clear ( 1 )  nearfar ( 3.04676e-05 3467.78 )  aspect ( 1.33333 )  pixelaspect ( 1 )  txyz ( 0 0 3.68246 )  pxyz ( 0 0 0 )  rotation ( 1 0 0 0 1.19209e-07 1 0 -1 1.19209e-07  )  homedistance ( 3.68246 )  homeadjboxwidth ( 2.22222 )  homeorthowidth ( 2.22222 )  homeradius ( 3.4641 )  homeaxis ( 0 )  homecustom ( 0.707107 -0.353553 0.612372 0 0.866025 0.5 -0.707107 -0.353553 0.612372  )  adjustlimits ( 1 )  
vieworthogrid -d off -o 0 0 0 -s 0.2 0.2 -r 5 5 -R 1 Build.panetab1.world.top1
viewuvgrid -r on -s 0.1 0.1 -P off -S 64 64 -O 0 0 -C on -t on Build.panetab1.world.top1
viewagentopts  -L on -b 0 -d 1 -l 0 -m 4 -p 1000 -w 1 Build.panetab1.world.top1
viewonionskin  -e on -a 4 -b 4 -i 6 -o 0.5 -A 1 1 1 -B 1 1 1 Build.panetab1.world.top1
viewposteffects  -D off -B off -t "" -f off -V off -S on -a 1 -b 5 -F 1 -g 1 -c 1 1 1 -C 1 1 1 -d 1e+06 -h 0 -H 100 10 -i 1 -I 1 -l 1 -n "" -o 1 -O 1 -r 0 1000 -R 1 200 -s 1 1 -u 0 -U 100 10 -v 0 Build.panetab1.world.top1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique scene Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r scene selectscene Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L off -G on -B none -d uv -r unique ghostscene Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w on -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique display Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w off -s wire -F off -l on -L off -G off -B none -d uv -r unique current Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s wire -F on -l on -L off -G on -B none -d uv -r unique template Build.panetab1.world.front1
viewdisplay -B light -b off -d off -C 2 -e 1 -F on -f off -g on -G '*' -h off -H on -j off -J off -L on -n 0.2 -o off -O on -q on -r on -s off -t on -V 2 -z off -y off -x off -X off -U 4 -Y 4 -T on -R on -i on -D on -k off Build.panetab1.world.front1
viewdisplay -Q on -m on -v on Build.panetab1.world.front1
viewdisplay -W  off 0 0 Build.panetab1.world.front1
viewdisplay -c on -l1 -K on -P points -p 3 Build.panetab1.world.front1
viewdispopts -a on -b current -c 1 -C 60  -d  on -D 1 -g on -i on -n on -N 1000000 -o off -p 10 -P off -r off -R off -S 512 -l 128 -m 0.05 -M 1024 -s on -t 0.5 -u uv -w 0.1 -W 0.9 -x on -X off Build.panetab1.world.front1
vieweffect -a 2 -A 4 -b on -B 0 -d on -D on off -e 0.8 -E -30 -30 -100 -f 1 -F 0 -g 2.2 -G 0 -h 1 -H on -i on -I 1 -j on -J 50 -K 2 -k 1 -l '' -m on -M 512 -o off -O 3 -p off -P 3 -q 1 -Q 2 -r 1024 1024 -s 2 -t 100 -T 100 -u off -U off -v 128 128 128 -w 0.05 -W off -x 0.4 0.4 0.4 -X 0.4 0.4 0.4 -y 0.4 0.4 0.4 -Y 0.0025 0.0025 0.0025 -z 0.01 -Z 0 Build.panetab1.world.front1
viewinfotext -m off -s off -t on Build.panetab1.world.front1
viewlight  -a on -d on -e on -h off -l on -n 8 -s on Build.panetab1.world.front1
viewbackground -b on -e on -q 1 -i off -m 0 0 -M 1 1 Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off persp Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off cam Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off top Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off front Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off right Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off bottom Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off back Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off left Build.panetab1.world.front1
viewroto  -S file -F '$HH/pic/uvgrid_grey.pic' -C '' -a on -o 0 0 -s 1 1 -B 0.2 -e off uv Build.panetab1.world.front1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off image Build.panetab1.world.front1
viewtransform Build.panetab1.world.front1 version ( 3 )  flag ( Fox )  orthowidth ( 2.22222 )  focal ( 50 )  aperture ( 41.4214 )  window ( 0 1 0 1 )  winroll ( 0 )  clear ( 1 )  nearfar ( 3.04676e-05 3467.78 )  aspect ( 1.33333 )  pixelaspect ( 1 )  txyz ( 0 0 3.68246 )  pxyz ( 0 0 0 )  rotation ( 1 0 0 0 1 0 0 0 1  )  homedistance ( 3.68246 )  homeadjboxwidth ( 2.22222 )  homeorthowidth ( 2.22222 )  homeradius ( 3.4641 )  homeaxis ( 0 )  homecustom ( 0.707107 -0.353553 0.612372 0 0.866025 0.5 -0.707107 -0.353553 0.612372  )  adjustlimits ( 1 )  
vieworthogrid -d off -o 0 0 0 -s 0.2 0.2 -r 5 5 -R 1 Build.panetab1.world.front1
viewuvgrid -r on -s 0.1 0.1 -P off -S 64 64 -O 0 0 -C on -t on Build.panetab1.world.front1
viewagentopts  -L on -b 0 -d 1 -l 0 -m 4 -p 1000 -w 1 Build.panetab1.world.front1
viewonionskin  -e on -a 4 -b 4 -i 6 -o 0.5 -A 1 1 1 -B 1 1 1 Build.panetab1.world.front1
viewposteffects  -D off -B off -t "" -f off -V off -S on -a 1 -b 5 -F 1 -g 1 -c 1 1 1 -C 1 1 1 -d 1e+06 -h 0 -H 100 10 -i 1 -I 1 -l 1 -n "" -o 1 -O 1 -r 0 1000 -R 1 200 -s 1 1 -u 0 -U 100 10 -v 0 Build.panetab1.world.front1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique scene Build.panetab1.world.right1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L on -G off -B none -d uv -r scene selectscene Build.panetab1.world.right1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s shade_wire -F off -l on -L off -G on -B none -d uv -r unique ghostscene Build.panetab1.world.right1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w on -s shade_wire -F off -l on -L on -G off -B none -d uv -r unique display Build.panetab1.world.right1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P on -p off -f off -o off -w off -s wire -F off -l on -L off -G off -B none -d uv -r unique current Build.panetab1.world.right1
viewdispset -m off always -n off always -c off always -u off always -x off always -N off always -C off always -b off always -M off always -v off always -V off always -U off always -h off -P off -p off -f off -o off -w off -s wire -F on -l on -L off -G on -B none -d uv -r unique template Build.panetab1.world.right1
viewdisplay -B light -b off -d off -C 2 -e 1 -F on -f off -g on -G '*' -h off -H on -j off -J off -L on -n 0.2 -o off -O on -q on -r on -s off -t on -V 2 -z off -y off -x off -X off -U 4 -Y 4 -T on -R on -i on -D on -k off Build.panetab1.world.right1
viewdisplay -Q on -m on -v on Build.panetab1.world.right1
viewdisplay -W  off 0 0 Build.panetab1.world.right1
viewdisplay -c on -l1 -K on -P points -p 3 Build.panetab1.world.right1
viewdispopts -a on -b current -c 1 -C 60  -d  on -D 1 -g on -i on -n on -N 1000000 -o off -p 10 -P off -r off -R off -S 512 -l 128 -m 0.05 -M 1024 -s on -t 0.5 -u uv -w 0.1 -W 0.9 -x on -X off Build.panetab1.world.right1
vieweffect -a 2 -A 4 -b on -B 0 -d on -D on off -e 0.8 -E -30 -30 -100 -f 1 -F 0 -g 2.2 -G 0 -h 1 -H on -i on -I 1 -j on -J 50 -K 2 -k 1 -l '' -m on -M 512 -o off -O 3 -p off -P 3 -q 1 -Q 2 -r 1024 1024 -s 2 -t 100 -T 100 -u off -U off -v 128 128 128 -w 0.05 -W off -x 0.4 0.4 0.4 -X 0.4 0.4 0.4 -y 0.4 0.4 0.4 -Y 0.0025 0.0025 0.0025 -z 0.01 -Z 0 Build.panetab1.world.right1
viewinfotext -m off -s off -t on Build.panetab1.world.right1
viewlight  -a on -d on -e on -h off -l on -n 8 -s on Build.panetab1.world.right1
viewbackground -b on -e on -q 1 -i off -m 0 0 -M 1 1 Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off persp Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off cam Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off top Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off front Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off right Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off bottom Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off back Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off left Build.panetab1.world.right1
viewroto  -S file -F '$HH/pic/uvgrid_grey.pic' -C '' -a on -o 0 0 -s 1 1 -B 0.2 -e off uv Build.panetab1.world.right1
viewroto  -S file -F '' -C '' -a on -o 0 0 -s 1 1 -B 1 -e off image Build.panetab1.world.right1
viewtransform Build.panetab1.world.right1 version ( 3 )  flag ( Fox )  orthowidth ( 2.22222 )  focal ( 50 )  aperture ( 41.4214 )  window ( 0 1 0 1 )  winroll ( 0 )  clear ( 1 )  nearfar ( 3.04676e-05 3467.78 )  aspect ( 1.33333 )  pixelaspect ( 1 )  txyz ( 0 0 3.68246 )  pxyz ( 0 0 0 )  rotation ( 6.12323e-17 0 1 0 1 0 -1 0 6.12323e-17  )  homedistance ( 3.68246 )  homeadjboxwidth ( 2.22222 )  homeorthowidth ( 2.22222 )  homeradius ( 3.4641 )  homeaxis ( 0 )  homecustom ( 0.707107 -0.353553 0.612372 0 0.866025 0.5 -0.707107 -0.353553 0.612372  )  adjustlimits ( 1 )  
vieworthogrid -d off -o 0 0 0 -s 0.2 0.2 -r 5 5 -R 1 Build.panetab1.world.right1
viewuvgrid -r on -s 0.1 0.1 -P off -S 64 64 -O 0 0 -C on -t on Build.panetab1.world.right1
viewagentopts  -L on -b 0 -d 1 -l 0 -m 4 -p 1000 -w 1 Build.panetab1.world.right1
viewonionskin  -e on -a 4 -b 4 -i 6 -o 0.5 -A 1 1 1 -B 1 1 1 Build.panetab1.world.right1
viewposteffects  -D off -B off -t "" -f off -V off -S on -a 1 -b 5 -F 1 -g 1 -c 1 1 1 -C 1 1 1 -d 1e+06 -h 0 -H 100 10 -i 1 -I 1 -l 1 -n "" -o 1 -O 1 -r 0 1000 -R 1 200 -s 1 1 -u 0 -U 100 10 -v 0 Build.panetab1.world.right1
viewsnapshotoption -s off -h off -a 1 -v '*' -m 0 Build.panetab1.world
cplane -o 0 0 0 -n 4.37114e-08 1 -4.37114e-08 -x 1.91069e-15 4.37114e-08 1 -l n -s 0.1 0.1 -c 40 40 -r 10 10 -d off Build.panetab1.world
glcache -t 1634 -v 6553
panepath -d Build -f -p panetab14 /obj/sphere_VASKOH
panepath -d Build -f -p panetab1 /obj/sphere_VASKOH
panepath -d Build -f -p panetab2 /obj/sphere_VASKOH
panepath -d Build -f -p panetab3 /obj/sphere_VASKOH
panepath -d Build -f -p panetab11 /obj/sphere_VASKOH
panepath -d Build -f -p panetab5 /obj/sphere_VASKOH
panepath -d Build -f -p panetab6 /obj/sphere_VASKOH
panepath -d Build -f -p panetab12 /obj/
panepath -d Build -f -p panetab7 /obj/sphere_VASKOH
panepath -d Build -f -p panetab8 /obj/
panepath -d Build -f -p panetab9 /obj/sphere_VASKOH
panepath -d Build -f -p panetab10 /obj/
desk set Build
radial menu set main
viewupdate -u always
audiopanel -s p ''
audiopanel -s r off
audiopanel -s s 24
audiopanel -s f 24
audiopanel -t p stop
audiopanel -t l off
audiopanel -t r on
audiopanel -o m off
audiopanel -o t on
audiopanel -o u on
audiopanel -o l 1
audiopanel -o r 1
audiopanel -o d 0
audiopanel -r d 0.2
audiopanel -m 0
audiopanel -a ''
audiopanel -f 1
audiopanel -O 0
colorsettings -D -A -g 2.2 -l "" -p -s -v -i -r -c -f
compproject -r 1920 1080 -a 1 -d fp16 -p 0 1 -P full -f 0 -F 0 -l on
texcache  -a off -r 2147483647 2147483647 -m 10000 -M 4085
shopvisible +I3D +VMantra +RIB
alias -u '__sesi_license__' '{
verification_id      1b075173
license_id           00000000043F8A10
lock			HAw0At0m5a+@H9escN4NrZaw3JrDUmxSw2fOr529fNX4nwFDMvoWfaWiNuG9DIVBeEpAqRQdlv5Hi5
data			000000010000000100000012000000052002077465MEN7ALX*.*.*.*1b075173
product_id           Houdini-Master
server_platform      Generic
support_expiry       2028-12-25
houdini_version      18005
available            199
count                200
ip_mask              *.*.*.*
display              MEN7ALX 0/1
}'

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".takes"
Content-Type: application/octet-stream
Content-Transfer-Encoding: base64

SG91ZGluaVRha2VGaWxlIDEuMAp0YWtlIG5hbWUgTWFpbiBraWRzIDAKAAAAAmUK

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".styles"
Content-Type: text/plain

NSJb{}
--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".contextoptions"
Content-Type: text/plain

[
]

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY
Content-Disposition: attachment; filename=".cwd"
Content-Type: text/plain

opcf /
takeset Main

--HOUDINIMIMEBOUNDARY0xD3ADD339-0x00000F49-0x56B122C9-0x00000001HOUDINIMIMEBOUNDARY--
